"use client";
import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { ArrowLeft, Mail } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { authApi } from "@/services/skinnerApi";
import { cleanText, isValidEmail } from "@/lib/formValidation";
export default function ForgotPasswordCard() { const navigate=useNavigate(); const [email,setEmail]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const submit=async(e)=>{e.preventDefault(); const cleanEmail=cleanText(email,120).toLowerCase(); if(!isValidEmail(cleanEmail)){setError("Enter a valid email address.");return;} setLoading(true); setError(""); try{await authApi.forgotPassword(cleanEmail); sessionStorage.setItem("skinner_reset_email",cleanEmail); navigate("/verify-code",{state:{email:cleanEmail}});}catch(apiError){setError(apiError.message||"Could not send the verification code.");}finally{setLoading(false);}}; return <Card className="w-full max-w-sm rounded-xl border border-gray-200 shadow-sm p-1"><CardContent className="p-5"><div className="flex items-center gap-3 mb-3"><button type="button" onClick={()=>navigate("/sign-in")} className="text-gray-500 hover:text-gray-900 transition-colors"><ArrowLeft className="h-5 w-5"/></button><h2 className="text-[16px] font-medium text-gray-900">Forgot Password</h2></div><p className="mt-1 text-[13px] text-gray-500 leading-relaxed mb-6">Enter your email address and we'll send you a verification code to reset your password</p><div className="flex items-start gap-3 rounded-lg border border-blue-100 bg-[#F4F8FF] p-3 mb-6"><Mail className="mt-0.5 h-4 w-4 shrink-0 text-black"/><p className="text-sm text-[#193CB8] leading-relaxed font-medium">A 6-digit verification code will be sent to your registered email address.</p></div><form onSubmit={submit} className="space-y-4"><div className="space-y-1.5"><Label className="text-[13px] text-gray-900 font-medium">Email Address</Label><Input type="email" value={email} onChange={(e)=>{setEmail(cleanText(e.target.value,120));setError("");}} placeholder="name@example.com" className={`h-9 text-[12px] ${error?"border-red-300":""}`}/>{error&&<p className="text-[10px] font-medium text-red-600">{error}</p>}</div><Button type="submit" disabled={loading} className="h-10 w-full bg-[#0B0B1F] text-[12px] hover:bg-[#16162b] disabled:opacity-60"><Mail className="h-4 w-4"/>{loading?"Sending...":"Send Verification Code"}</Button></form><div className="mt-4 text-center text-[11px] text-gray-500">Remember your password? <Link to="/sign-in" className="text-blue-600 hover:underline">Sign in here</Link></div></CardContent></Card>; }
