import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext(null);

const dictionary = {
  en: {
    // Navbar
    home: "Home",
    features: "Features",
    contact_us: "Contact Us",
    sign_in: "Sign In",
    register: "Register",
    logout: "Logout",
    language: "Language",
    english: "English",
    arabic: "العربية",
    
    // Footer
    medical_disclaimer_title: "Medical Disclaimer:",
    medical_disclaimer_desc: "Skin Disease Detection System is designed to assist in skin condition identification but should not replace professional medical advice, diagnosis, or treatment.",
    medical_disclaimer_advice: "Always seek the advice of your physician or other qualified health provider with any questions regarding a medical condition.",
    footer_copyright: "© 2024 Skin Disease Detection System. HIPAA Compliant Healthcare Platform.",

    // Auth & Forms
    email: "Email Address",
    password: "Password",
    forgot_password: "Forgot Password?",
    sign_in_btn: "Sign In",
    register_btn: "Register",
    full_name: "Full Name",
    phone: "Phone Number",
    gender: "Gender",
    male: "Male",
    female: "Female",
    age: "Age",
    address: "Address",
    national_id: "National ID",
    specialization: "Specialization",
    experience: "Years of Experience",
    clinic_address: "Clinic Address",
    consultation_fee: "Consultation Fee",
    syndicate_card: "Syndicate Card Image",
    patient: "Patient",
    doctor: "Doctor",
    register_as_patient: "Register as Patient",
    register_as_doctor: "Register as Doctor",
    sign_in_card_title: "Sign In",
    sign_in_card_desc: "Enter your credentials to access your account",
    i_am_a: "I am a",
    select_role: "Select role",
    remember_me: "Remember me",
    signing_in: "Signing in...",
    dont_have_account: "Don't have an account?",
    register_here: "Register here",
    forgot_password_title: "Forgot Password",
    forgot_password_desc: "Enter your email to receive a password reset verification code",
    forgot_password_desc_ext: "Enter your email address and we'll send you a verification code to reset your password",
    verify_otp_info: "A 6-digit verification code will be sent to your registered email address.",
    send_verification_code: "Send Verification Code",
    remember_password: "Remember your password?",
    send_code: "Send Code",
    sending: "Sending...",
    back_to_sign_in: "Back to Sign In",
    verify_otp_title: "Verify Code",
    verify_otp_desc: "We sent a 6-digit code to your email",
    verify_otp_desc_sent: "Enter the 6-digit verification code sent to",
    verify_btn: "Verify Code",
    verifying: "Verifying...",
    resend_code: "Resend Code",
    resend_in: "Resend in",
    reset_password_title: "Reset Password",
    reset_password_desc: "Create a new strong password for your account",
    reset_password_desc_for: "Create a new strong password for",
    new_password: "New Password",
    confirm_password: "Confirm New Password",
    reset_btn: "Reset Password",
    resetting: "Resetting...",
    code_expires_in: "Code expires in:",
    code_expired: "Code expired.",
    code_expired_desc: "Please resend to get a new code.",
    identity_verified: "Your identity has been verified. Please create a new password.",
    password_requirements: "Password Requirements:",
    pwd_req_1: "At least 6 characters",
    pwd_req_2: "Use a mix of letters, numbers, and symbols",
    return_to_login: "Return to login",
    verify_code_desc: "A 6-digit verification code will be sent to your registered email address.",
    didnt_receive_code: "Didn't receive the code?",

    // Features Section & CTA Section
    why_choose_system: "Why Choose Skin Disease Detection System?",
    feature_ai_title: "AI-Powered Analysis",
    feature_ai_desc: "Advanced machine learning algorithms provide instant preliminary skin condition identification",
    feature_expert_title: "Expert Verification",
    feature_expert_desc: "All AI results are reviewed by verified dermatology specialists",
    feature_secure_title: "Secure & Private",
    feature_secure_desc: "HIPAA-compliant platform ensuring your health data remains confidential",
    feature_matching_title: "Doctor Matching",
    feature_matching_desc: "Get connected with the right specialists based on your condition",
    for_professionals: "For Healthcare Professionals",
    professionals_desc: "Join our network of verified doctors and help patients get the care they need",
    benefit_1: "Access AI-analyzed patient cases",
    benefit_2: "Streamlined patient management",
    benefit_3: "Expand your practice reach",
    start_now: "Start Now",

    // Features Page
    platform_features: "Platform Features",
    everything_needed_title: "Everything You Need for",
    skin_health: " Skin Health",
    platform_desc: "From AI-powered diagnosis to verified doctor consultations, Skinner brings together cutting-edge technology and medical expertise in one seamless platform.",
    stat_ai: "AI-Powered",
    stat_ai_label: "Skin Analysis",
    stat_verified: "Verified",
    stat_verified_label: "Dermatologists",
    stat_enc: "End-to-End",
    stat_enc_label: "Encryption",
    stat_247: "24/7",
    stat_247_label: "AI Assistant",
    feat_ai_title: "AI Skin Analysis",
    feat_ai_desc: "Upload a photo of your skin condition and receive an instant AI-powered preliminary diagnosis with confidence score — all in seconds.",
    feat_dr_title: "Verified Dermatologists",
    feat_dr_desc: "Browse a network of verified, board-certified dermatologists. View their specialties, experience, ratings, and clinic locations before booking.",
    feat_chat_title: "Secure Doctor-Patient Chat",
    feat_chat_desc: "Communicate with your dermatologist through end-to-end encrypted messaging. Share images, files, and documents directly within the conversation.",
    feat_booking_title: "Smart Appointment Booking",
    feat_booking_desc: "Book appointments with real-time availability. Select your preferred date and time slot, view the doctor's schedule, and confirm instantly.",
    feat_payment_title: "Secure Payments with OTP",
    feat_payment_desc: "Pay for consultations securely with PCI-DSS compliant processing. Every transaction is verified with a one-time password (OTP) for maximum security.",
    feat_bot_title: "AI Health Assistant",
    feat_bot_desc: "Get instant answers about skin conditions, treatment options, and platform guidance from our HIPAA-compliant AI chatbot — available 24/7.",
    feat_report_title: "Medical Reports & Downloads",
    feat_report_desc: "Doctors can write detailed medical reports directly within the platform. Patients receive downloadable reports and can review their diagnosis history.",
    feat_upload_title: "Image Upload & Case Review",
    feat_upload_desc: "Patients upload skin images for analysis. Doctors review cases with full patient information and AI predictions before consulting.",
    feat_map_title: "Clinic Location Maps",
    feat_map_desc: "View your doctor's clinic on an interactive Google Maps embed. Get directions to the exact address for your in-person appointment.",
    feat_dash_title: "Doctor Dashboard & Analytics",
    feat_dash_desc: "Doctors manage pending and reviewed cases, set availability schedules, and track patient analytics — all from a unified dashboard.",
    feat_privacy_title: "Privacy & Data Protection",
    feat_privacy_desc: "All conversations are end-to-end encrypted. Medical data is handled with HIPAA-compliant standards. Your health information stays private.",
    feat_library_title: "Analysis Library",
    feat_library_desc: "Access a comprehensive library of past analyses and skin condition information. Track your skin health journey with a complete history of results.",
    ready_control: "Ready to Take Control of Your Skin Health?",
    join_skinner_desc: "Join Skinner today and get access to AI-powered skin analysis, verified dermatologists, and secure medical consultations — all in one platform.",
    get_started_free: "Get Started Free",

    // Contact Us Page
    contact_desc: "Have questions about Skinner? Reach out to our team — we're here to help you with anything related to skin health and our platform.",
    phone_numbers: "Phone Numbers",
    email_addresses: "Email Addresses",
    our_location: "Our Location",
    egypt_cairo_alex: "Egypt — Cairo & Alexandria",
    serving_patients_region: "Serving patients across the region with AI-powered dermatology.",
    working_hours: "Working Hours",
    sunday_thursday: "Sunday – Thursday",
    friday_saturday: "Friday – Saturday",
    nine_to_six: "9:00 AM – 6:00 PM",
    closed: "Closed",
    need_immediate_assistance: "Need Immediate Assistance?",
    immediate_assistance_desc: "For urgent medical concerns, please contact your nearest healthcare provider or call emergency services.",
    call_us_now: "Call Us Now",
    
    // Portal General
    patient_portal: "Patient Portal",
    doctor_portal: "Doctor Portal",
    admin_portal: "Admin Portal",
    
    // Stats & Tabs
    pending_reviews: "Pending Reviews",
    finished_cases: "Finished Cases",
    total_patients: "Total Patients",
    cases_awaiting_review: "Case awaiting review",
    cases_completed: "Cases completed",
    total_patients_served: "Total patients served",
    no_patients_yet: "No patients yet",
    
    pending_cases_tab: "Pending Cases",
    finished_cases_tab: "Finished Cases",
    schedule_tab: "Schedule",
    
    // Case details & Card
    case_review_title: "Case Review",
    submitted_on: "Submitted on",
    back_to_list: "Back to List",
    patient_info: "Patient Information",
    ai_analysis: "AI Analysis",
    confidence_level: "Confidence Level",
    write_report: "Write Report",
    view_report: "View Report",
    edit_report: "Edit Report",
    start_chat: "Start Chat with Patient",
    continue_chat: "Continue Chat",
    read_chat: "Read Chat",
    follow_up_chat: "Follow-Up Chat",
    ai_diagnosis: "AI Diagnosis",
    confidence: "confidence",
    yrs: "yrs",
    review_case: "Review Case",
    chat_with_patient: "Chat with Patient",
    
    // Chat & Summary Card
    clinical_summary: "Clinical Summary",
    ai_prediction: "AI Prediction",
    analysis_date: "Analysis Date",
    view_skin_scan: "View Skin Scan",
    secure: "SECURE",
    chat_locked: "This chat is locked because the follow-up period has expired.",
    type_message: "Type your message...",
    send: "Send",
    
    // Home Page
    hero_title: "Revolutionizing Dermatological Diagnostics",
    hero_subtitle: "Access advanced AI skin disease classifications and consult top dermatologists instantly from the comfort of your home.",
    get_started: "Get Started",
    learn_more: "Learn More",
    features_title: "Why Choose Skinner?",
    features_desc: "We bring together cutting-edge AI and certified medical professionals to provide immediate, reliable skin health support.",
    
    // Patient Portal Tabs & Elements
    upload_tab: "Upload",
    analysis_tab: "Analysis",
    doctors_tab: "Doctors",
    chat_tab: "Chat",
    patient_tab: "Patient",
    library_tab: "Library",
    previous: "Previous",
    next: "Next",
    scan_history: "Skin Scan History",
    no_analyses_yet: "You haven't scanned any skin conditions yet.",
    view_details: "View Details",
    confidence_score: "Confidence Score",
    find_doctors: "Find Doctors",
    start_new_analysis: "Start New Analysis",
    ai_health_assistant: "AI Health Assistant",
    ai_assistant_desc: "Ask any questions about skin conditions, general symptoms, or platform usage.",
    type_ai_question: "Ask the AI assistant a question...",
    see_more: "See More",
    all_analyses: "All Previous Analyses",
    no_image: "No image",
    no_analyses_desc: "You do not have any saved analyses yet. Upload an image to generate a skin analysis.",
    refresh: "Refresh",
    
    // Upload Skin Image Card
    tip_1: "Ensure good lighting without shadows",
    tip_2: "Take photo perpendicular to the skin surface",
    tip_3: "Include a reference object for scale if possible",
    tip_4: "Avoid using flash when possible",
    tip_5: "Capture the entire affected area",
    upload_skin_image: "Upload Skin Image",
    upload_skin_desc: "Take a clear photo or upload an image of the affected area for AI analysis",
    best_results: "For best results:",
    upload_from_device: "Upload from Device",
    browse_files: "Click to browse files",
    take_photo: "Take Photo",
    use_camera: "Use your camera",
    supported_formats: "Supported formats: JPG, PNG, HEIC - Max file size:",
    saved_image_title: "Saved Image - Ready for Analysis",
    saved_image_desc: "Your image has been securely saved and is ready for AI analysis",
    ai_progress_title: "AI Analysis in Progress",
    ai_progress_desc: "Analyzing your skin image",
    analyzing: "Analyzing...",
    analyze_with_ai: "Analyze Image with AI",
    upload_new_image: "Upload New Image",
    retake_photo: "Retake Photo",
    close: "Close",
    
    // Register Extra
    register_desc: "Register as a patient, healthcare provider, or admin",
    already_have_account: "Already have an account?",
    sign_in_here: "Sign in here",
    upload_id: "Upload your ID",
    invite_code: "Invite Code",
    register_as_admin: "Register as Admin",
    terms_policy_agreement: "By registering, you agree to our Terms of Service and Privacy Policy.",
    doctor_review_agreement: "Your registration will be reviewed by our admin team.",
    admin_invite_warning: "Administrator Registration: Admin accounts require authorization and invite code.",

    // Messages & Alerts
    report_submitted: "Report Submitted",
    all_reports: "All Reports",
    report_doctor: "Report {name}",
    select_date_time_error: "Please select a valid date and time before proceeding.",
    availability_load_error: "Could not load doctor availability from API. Please try again later.",
    upload_analysis_required: "Please upload and analyze a skin image before booking an appointment.",
    booking_failed: "Could not book appointment.",
    doctors_load_error: "Could not load doctors from API. Please try again later.",
    missing_appointment_id: "Missing appointment ID. Please book the appointment again.",
    payment_failed: "Payment failed. Please try again.",
    message_send_failed: "Message could not be sent to the API.",
    ai_welcome: "Hello {name}! I'm your AI Health Assistant. I can help answer questions about your skin condition, provide general health information, and guide you through the platform. How can I assist you today?",
    no_conversations_yet: "No conversations yet",
    no_conversations_desc: "Your chats with doctors will appear here after booking an appointment.",
    no_messages_yet: "No messages yet. Say hello to your doctor!",
    download_report: "Download Report",
    my_conversations: "My Conversations",
    chat_securely_desc: "Chat with your doctors securely",
    high_confidence: "High Confidence",
    medium_confidence: "Medium Confidence",
    low_confidence: "Low Confidence",
    file_size_error: "File size must be under 10 MB.",

    // Added for Dashboards & Pages
    see_more: "See More",
    all_analyses: "All Previous Analyses",
    no_image: "No image",
    no_analyses_desc: "You do not have any saved analyses yet. Upload an image to generate a skin analysis.",
    refresh: "Refresh",
    previous_analyses: "Previous Analyses",
    no_previous_analyses: "No previous analyses",
    loaded_from_api: "Loaded from API",
    no_analyses_found: "No analyses found.",
    could_not_load_analyses: "Could not load previous analyses.",
    unknown_condition: "Unknown condition",
    confidence_suffix: "Confidence",
    high: "High",
    medium: "Medium",
    low: "Low",
    more: "more",
    loading_analysis: "Loading analysis...",
    unable_to_load_analysis: "Unable to load analysis",
    retry: "Retry",
    no_analysis_available: "No Analysis Available",
    upload_to_receive_ai: "Upload a skin image to receive an AI-powered analysis.",
    start_analysis: "Start Analysis",
    ai_analysis_results: "AI Analysis Results",
    analysis_completed_on: "Analysis completed on",
    analysis_completed_unknown: "on an unknown date",
    ai_powered: "AI-Powered",
    medical_disclaimer_capital: "Medical Disclaimer:",
    medical_disclaimer_detailed: "This AI analysis is for informational purposes only and should not replace professional medical advice. Please consult with a qualified healthcare provider for proper diagnosis and treatment.",
    analyzed_image: "Analyzed Image",
    no_image_available: "No image available",
    primary_detection: "Primary Detection",
    condition_unavailable: "Condition unavailable",
    analysis_status: "Analysis Status",
    analysis_complete: "Analysis Complete",
    description: "Description",
    no_description_available: "No description is available for this analysis.",
    ai_recommendations: "AI Recommendations",
    no_recommendations_available: "No specific recommendations available for this analysis. Please consult a dermatologist for personalized advice.",
    alternative_detections: "Alternative Detections",
    no_alternative_detections: "No significant alternative detections found.",
    next_step_consult: "Next Step: Consult a Specialist",
    consult_recommendation: "Based on your analysis results, we recommend consulting with a dermatology specialist for a comprehensive evaluation and personalized treatment plan.",
    find_recommended_doctors: "Find Recommended Doctors",
    hipaa_compliant_encrypted: "HIPAA Compliant • Encrypted",
    chatbot_warning: "This chatbot provides general information only and is not a substitute for professional medical advice.",
    powered_by_ai: "Powered by AI • End-to-end encrypted",
    encrypted: "Encrypted",
    ai_assistant_unavailable: "The AI assistant is currently unavailable. Please try again later.",
    ai_no_answer: "I received your message, but no answer was returned from the chatbot service.",
    no_library_content: "No library content available",
    no_library_content_desc: "The skin disease library is currently empty because no backend data is available.",
    skin_disease_library: "Skin Disease Library",
    definition: "Definition",
    common_in: "Common in",
    symptoms: "Symptoms",
    back_to_library: "Back to Library",
    definition_colon: "Definition:",
    common_in_colon: "Common in:",
    symptoms_colon: "Symptoms:",
    pending_payment: "Pending Payment",
    confirmed: "Confirmed",
    cancelled: "Cancelled",
    completed: "Completed",
    reviewed: "Reviewed",
    appointment_schedule: "Appointment Schedule",
    appointment_day: "Appointment Day",
    today: "Today",
    upcoming_appointments: "Upcoming Appointments",
    no_upcoming_appointments: "No upcoming appointments",
    pay_now: "Pay Now",
    patient_information: "Patient Information",
    edit: "Edit",
    save_changes: "Save Changes",
    cancel: "Cancel",
    profile_updated: "Patient profile updated successfully.",
    profile_load_error: "Could not load patient data from API. Please try again later.",
    profile_update_error: "Profile could not be updated on the API.",
    appointment_details: "Appointment Details",
    dermatologist: "Dermatologist",
    date: "Date",
    time: "Time",
    open_in_google_maps: "Open in Google Maps",
    related_scan_analysis: "Related Scan Analysis",
    ai_skin_classification: "AI Skin Classification",
    available_specialists: "Available Specialists",
    browse_verified_doctors: "Browse verified doctors registered on the platform and book an appointment.",
    loading_doctors_api: "Loading doctors from API...",
    no_specialists_available: "No specialists available",
    no_specialists_desc: "We could not find any doctors for your request right now. Please check back later.",
    book_appointment: "Book Appointment",
    verified: "Verified",
    no_address_available: "No address available",
    no_doctor_selected: "No doctor selected",
    select_doctor_first: "Select a doctor from the recommendations before viewing the map.",
    back_to_doctors: "Back to Doctors",
    recommended_specialists: "Recommended Specialists",
    back: "Back",
    clinic: "Clinic",
    contact: "Contact",
    not_available: "Not available",
    hours_not_available: "Hours not available",
    years_experience: "{n} years experience",
    doctor: "Doctor",
    specialty_dermatology: "Dermatology",
    specialty_pediatric_dermatology: "Pediatric Dermatology",
    specialty_cosmetic_surgery: "Cosmetic Surgery",
    address_cairo: "Cairo",
    address_nile_st_cairo: "Nile St, Cairo",
    currency_format: "{val} EGP",
    currency_unit: "EGP",
    amount_paid: "Amount Paid",
    select_date: "Select Date",
    choose_available_date: "Choose an available date for your appointment",
    loading_available_dates: "Loading available dates...",
    no_available_dates: "No available dates for this doctor.",
    select_time_slot: "Select Time Slot",
    available_slots_for: "Available time slots for",
    loading_available_slots: "Loading available slots...",
    no_available_slots: "No available time slots for this date.",
    morning: "Morning",
    afternoon: "Afternoon",
    selected: "Selected",
    available: "Available",
    unavailable: "Unavailable",
    appointment_summary: "Appointment Summary",
    in_person_at: "In-person at",
    booking_dots: "Booking...",
    proceed_to_payment: "Proceed to Payment",
    redirect_payment_notice: "You will be redirected to a secure payment page to complete your booking. No charges will be made until you confirm the payment.",
    prices_include_tax: "Prices Include 20% Tax",
    booking_fee: "Booking Fee",
    tax: "Tax",
    total: "Total",
    cancellation_policy: "Cancellation Policy:",
    cancellation_policy_desc: "Free cancellation up to 24 hours before appointment. 50% refund for cancellations within 24 hours.",
    card_number: "Card Number",
    cardholder_name: "Cardholder Name",
    expiry_date: "Expiry Date",
    cvv: "CVV",
    secure_payment: "Secure Payment",
    payment_encrypted_desc: "Your payment information is encrypted and secure",
    pci_dss_compliant: "PCI DSS Compliant:",
    pci_dss_desc: "All transactions are encrypted using industry-standard 256-bit SSL encryption. Your card details are never stored on our servers.",
    save_card_future: "Securely save this card for future appointments",
    otp_sent: "OTP Sent!",
    otp_sent_desc: "A 6-digit verification code has been sent to the phone number linked to your credit card.",
    enter_otp: "ENTER OTP Code",
    code_expires: "Code expires in",
    resend_otp: "Resend OTP",
    security_verification_title: "Security Verification:",
    security_verification_desc: "After clicking “Confirm Payment”, a One-Time Password (OTP) will be sent to the phone number linked to your credit card for security verification.",
    confirm_payment: "Confirm Payment",
    processing: "Processing...",
    final_payment_confirmation: "Final Payment Confirmation",
    payment_agreement_desc: "By confirming this payment, you agree to our Terms of Service and Privacy Policy. Your payment is secured with 256-bit SSL encryption and OTP verification.",
    we_accept: "We accept:",
    back_appointment_selection: "Back to Appointment Selection",
    payment_successful: "Payment Successful!",
    payment_success_desc: "Your appointment has been confirmed and a confirmation email has been sent.",
    appointment_confirmation: "Appointment Confirmation",
    save_records_desc: "Please save this information for your records",
    confirmation_number: "Confirmation Number:",
    download_receipt: "Download Receipt",
    add_to_calendar: "Add to Calendar",
    whats_next: "What's Next?",
    email_confirmation_title: "Confirmation Email",
    email_confirmation_desc: "A detailed confirmation email with appointment instructions has been sent to your registered email address.",
    calendar_reminder_title: "Calendar Reminder",
    calendar_reminder_desc: "Add this appointment to your calendar to receive reminders 24 hours and 1 hour before your appointment.",
    arrive_early_title: "Arrive 15 Minutes Early",
    arrive_early_desc: "Please arrive at the clinic 15 minutes before your scheduled appointment time for check-in.",
    prepare_info_title: "Prepare Your Information",
    prepare_info_desc: "Bring any relevant medical records, previous test results, and a list of current medications to your appointment.",
    need_changes_title: "Need to Make Changes?",
    need_changes_desc: "If you need to reschedule or cancel your appointment, please contact us at least 24 hours in advance.",
    chat_with_this_doctor: "Chat with this doctor",
    return_to_dashboard: "Return to Dashboard",
    tap_to_open_conv: "Tap to open conversation",
    report_available: "Report available",
    chat_closes_in: "Follow-up period is active. Chat closes in",
    chat_locked_new_appt: "Chat is locked. Book a new appointment with this doctor to reopen.",
    empty_message: "(empty message)",
    view_skin_scan: "View Skin Scan",
    cases_unread: "Cases",
    pending_cases: "Pending Cases",
    finished_cases: "Finished Cases",
    schedule: "Schedule",
    case_review_colon: "Case Review:",
    case_closed_expired: "This case is closed. The follow-up period has expired, and no medical report was submitted.",
    report_required_passed: "Report Required: The appointment date has passed. Please write and submit the medical report before the follow-up period expires.",
    patient_image: "Patient Image",
    report_not_submitted: "Report Not Submitted",
    view_edit_report: "View & Edit Report",
    download_receipt_txt: "Download Receipt",
    get_report: "Get Report",
    write_report: "Write Report",
    enter_notes_comments: "Enter verification notes and comments...",
    back_to_chat: "Back to Chat",
    save: "Save",
    saving_dots: "Saving…",
    remove_day: "Remove Day",
    no_slots_set: "No time slots set — add one below",
    time_slot_one: "time slot",
    time_slots_many: "time slots",
    add_slot: "Add Slot",
    select_date_calendar_desc: "Select a date on the calendar to set your available hours",
    click_date_available: "Click a date to set your available hours",
    has_availability: "Has Availability",
    start: "Start",
    end: "End",
    slot: "Slot",
    remove_time_slot: "Remove this time slot",
    doctor_information: "Doctor Information",
    total_users: "Total Users",
    no_users_yet: "No users yet",
    registered_users: "Registered users",
    active_doctors: "Active Doctors",
    no_active_doctors: "No active doctors",
    verified_professionals: "Verified professionals",
    pending_approvals: "Pending Approvals",
    none_pending: "None pending",
    require_verification: "Require verification",
    ai_analyses: "AI Analyses",
    total_analyses_performed: "Total analyses performed",
    conditions_found: "Conditions Found",
    condition_breakdown: "Condition Breakdown",
    no_analysis_data: "No analysis data available yet.",
    recent_analyses: "Recent Analyses",
    no_analyses_recorded: "No analyses recorded yet.",
    search_users_placeholder: "Search by name, email, or phone...",
    all_filter: "All",
    patients_filter: "Patients",
    doctors_filter: "Doctors",
    no_users_found: "No users found",
    no_users_match: "No registered users match your search criteria.",
    registered_colon: "Registered:",
    specialization_bold: "Specialization:",
    experience_bold: "Experience:",
    clinic_address_bold: "Clinic Address:",
    generate_admin_code: "Generate Admin Invite Code",
    generate_admin_code_desc: "Generate a one-time invite code that can be used to register a new admin account. Each code can only be used once.",
    generating_dots: "Generating...",
    generate_new_code: "Generate New Code",
    admin_code_generated_success: "Admin invite code generated successfully!",
    admin_code_generated_fail: "Code was generated but could not be read from the response.",
    admin_code_generated_fail_err: "Failed to generate admin invite code.",
    generated_invite_code: "Generated Invite Code",
    copied_excl: "Copied!",
    copy: "Copy",
    share_code_desc: "Share this code with the new admin. It can only be used once for a single registration.",
    no_active_invite_code: "No Active Invite Code",
    missing_syndicate_id: "Missing doctor syndicate ID.",
    admin_action_fail: "Admin action failed. Please try again.",
    doctor_approved_success: "Doctor approved successfully.",
    doctor_rejected_success: "Doctor rejected successfully.",
    working_dots: "Working...",
    confirm_approval: "Confirm Approval",
    confirm_rejection: "Confirm Rejection",
    approve_confirm_question: "Are you sure you want to approve {name}? This will activate their account.",
    reject_confirm_question: "Are you sure you want to reject {name}? This action will be logged.",
    confirm_btn: "Confirm",
    approve_activate_btn: "Approve & Activate Account",
    reject_application_btn: "Reject Application",
    verify_doctor_colon: "Verify Doctor:",
    verify_alert_desc: "Please verify the medical credentials before approving this application. All information will be cross-checked with medical licensing databases.",
    verification_notes: "Verification Notes",
    this_doctor: "this doctor",
    pending: "Pending",
    verify_info_id: "Verify ID Document",
    doctor_id_title: "Doctor ID",
    id_doctor_placeholder: "Doctor ID",
    review_application_btn: "Review Application",
    submission_date: "Submission Date",
    approved: "Approved",
    rejected: "Rejected",
    years: "years",
    minute: "minute",
    minutes: "minutes",
    second: "second",
    seconds: "seconds",
    doctor_verification: "Doctor Verification",
    user_management: "User Management",
    analytics: "Analytics",
    invite_codes: "Invite Codes",
    could_not_load_analytics: "Could not load analytics data. Please try again.",
    could_not_load_pending: "Could not load pending doctors from API.",
    could_not_load_users: "Could not load users directory from API.",
    could_not_load_admin: "Could not load admin portal data. Please try again.",
    no_pending_doctors: "No pending doctors",
    no_pending_doctors_desc: "No doctor verifications are awaiting review right now.",
    dermatology: "Dermatology",
    invite_code_used_success: "Invite code {code} was successfully used by {email}!",
    new_admin: "new admin",

    // ─── Disease titles (all 16 AI model conditions) ───
    moles_title: "Moles (Melanocytic Nevi)",
    acne_title: "Acne Vulgaris",
    actinic_keratosis_title: "Actinic Keratosis",
    bullous_title: "Bullous Disease",
    drugeruption_title: "Drug Eruption",
    eczema_title: "Eczema (Atopic Dermatitis)",
    lichen_title: "Lichen Planus",
    lupus_title: "Lupus (Cutaneous)",
    rosacea_title: "Rosacea",
    seborrh_keratoses_title: "Seborrheic Keratosis",
    skincancer_title: "Skin Cancer",
    tinea_title: "Tinea (Ringworm)",
    unknown_normal_title: "Unknown / Normal",
    vasculitis_title: "Vasculitis",
    vitiligo_title: "Vitiligo",
    warts_title: "Warts (HPV)",

    // ─── Disease descriptions (full patient-facing text) ───
    moles_description: "Moles (melanocytic nevi) are common skin growths that appear as small, dark brown spots caused by clusters of pigment-forming cells. Most moles are harmless and rarely become cancerous. They can appear anywhere on the body, alone or in groups, and most develop by age 40. While the vast majority of moles are benign, it is important to monitor them for changes.",
    acne_description: "Acne is a common skin condition that occurs when hair follicles become clogged with oil and dead skin cells. It often causes pimples, blackheads, or whiteheads and typically appears on the face, forehead, chest, upper back, and shoulders. Acne is most common among teenagers but can affect people of all ages.",
    actinic_keratosis_description: "Actinic keratosis is a rough, scaly patch on the skin caused by years of sun exposure. It usually appears on sun-exposed areas like the face, lips, ears, forearms, scalp, and neck. While it is not cancer, it is considered a precancerous condition because it can sometimes develop into squamous cell carcinoma if left untreated.",
    bullous_description: "Bullous disease refers to a group of conditions that cause large, fluid-filled blisters on the skin. These blisters can appear on areas of skin that flex, such as the lower abdomen, upper thighs, or armpits. The condition can be uncomfortable and may increase the risk of skin infections if blisters break open.",
    drugeruption_description: "A drug eruption is a skin reaction caused by a medication you are taking. It can appear as red rashes, hives, blisters, or widespread skin irritation. The reaction may start within days of beginning a new medication or even after taking a medicine for a long time. Symptoms often improve once the causing medication is stopped.",
    eczema_description: "Eczema (atopic dermatitis) is a chronic condition that makes the skin red, itchy, and inflamed. It often appears in patches on the hands, feet, ankles, wrists, neck, upper chest, eyelids, and inside the bend of elbows and knees. While there is no cure, proper management can control flare-ups and keep the skin comfortable.",
    lichen_description: "Lichen planus is an inflammatory condition that affects the skin, hair, nails, and mucous membranes. On the skin, it usually appears as purplish, flat-topped, itchy bumps. It can also cause lacy white patches, sores, or painful areas in the mouth. The condition is not contagious and is thought to be related to the immune system.",
    lupus_description: "Lupus skin involvement (cutaneous lupus) causes various rashes and sores on the skin, including the characteristic butterfly-shaped rash across the cheeks and nose. It is an autoimmune condition where the body's immune system attacks healthy tissue. Skin symptoms may be the first sign of lupus and can be triggered or worsened by sun exposure.",
    rosacea_description: "Rosacea is a chronic skin condition that causes redness, visible blood vessels, and sometimes small, pus-filled bumps on the face. It most commonly affects the cheeks, nose, chin, and forehead. Symptoms may flare up for weeks or months and then go away for a while. Without treatment, rosacea tends to worsen over time.",
    seborrh_keratoses_description: "Seborrheic keratosis is a common, harmless (non-cancerous) skin growth that usually appears as a brown, black, or tan waxy, slightly raised patch. They often look as if they are stuck on the skin and can appear on the face, chest, shoulders, or back. While they are not dangerous, they can sometimes be confused with skin cancer.",
    skincancer_description: "The analysis has detected features consistent with skin cancer. Skin cancer is the abnormal growth of skin cells, most often developing on skin exposed to the sun. Early detection and treatment are critical for the best outcomes. Please do not delay — a professional medical evaluation is strongly recommended.",
    tinea_description: "Tinea (ringworm) is a common fungal infection of the skin, not caused by a worm despite the name. It usually appears as a circular, red, scaly, and itchy patch with clearer skin in the center, forming a ring shape. It can appear on the body, scalp, feet (athlete's foot), or groin area and is contagious through skin contact or shared items.",
    unknown_normal_description: "The AI analysis did not detect any of the 15 specific skin conditions it is trained to identify. This could mean the skin appears normal, or the condition is outside the scope of what the AI model covers. This result does not rule out all skin conditions.",
    vasculitis_description: "Vasculitis is a condition involving inflammation of blood vessels. When it affects the skin, it can cause red or purple spots, bumps, or patches. In some cases, the skin changes may indicate a more widespread condition affecting other organs. The severity varies widely depending on the type and extent of blood vessel involvement.",
    vitiligo_description: "Vitiligo is a condition in which patches of skin lose their color (pigment), resulting in smooth, white areas. It occurs when the cells that produce melanin (skin pigment) are destroyed by the immune system. Vitiligo can affect any area of the body and may spread over time. It is not contagious or physically harmful, but can have an emotional impact.",
    warts_description: "Warts are small, rough, grainy skin growths caused by the human papillomavirus (HPV). They are most common on the fingers and hands but can appear anywhere on the body. Warts are contagious and can spread through direct skin contact or contaminated surfaces. Most warts are harmless and may go away on their own over time, though treatment can speed up removal.",

    // ─── Disease recommendations (arrays serialized as individual keys) ───
    moles_rec_1: "Monitor your moles regularly for changes in size, shape, color, or symmetry (use the ABCDE rule)",
    moles_rec_2: "Protect moles from sun exposure by applying sunscreen (SPF 30+) and wearing protective clothing",
    moles_rec_3: "Do not attempt to remove or scratch moles at home — this may cause infection or scarring",
    moles_rec_4: "See a dermatologist if a mole changes appearance, bleeds, itches, or becomes painful",
    moles_rec_5: "Consider annual skin exams with a dermatologist, especially if you have many moles or a family history of skin cancer",
    acne_rec_1: "Wash the affected area gently twice daily with a mild, fragrance-free cleanser",
    acne_rec_2: "Avoid touching, picking, or squeezing pimples to prevent scarring and infection",
    acne_rec_3: "Use non-comedogenic (won't clog pores) moisturizers and sunscreens",
    acne_rec_4: "Consider over-the-counter treatments containing benzoyl peroxide or salicylic acid",
    acne_rec_5: "Consult a dermatologist if acne is severe, painful, or not improving with basic care",
    actinic_keratosis_rec_1: "Apply broad-spectrum sunscreen (SPF 30+) daily, even on cloudy days",
    actinic_keratosis_rec_2: "Wear protective clothing, hats, and sunglasses when outdoors",
    actinic_keratosis_rec_3: "Schedule a dermatology appointment for professional evaluation as soon as possible",
    actinic_keratosis_rec_4: "Avoid tanning beds and prolonged direct sun exposure",
    actinic_keratosis_rec_5: "Monitor the affected area for changes in size, color, or texture and report them to your doctor",
    bullous_rec_1: "Do not pop or puncture blisters — keep them intact to prevent infection",
    bullous_rec_2: "Keep the affected area clean and gently covered with sterile bandages",
    bullous_rec_3: "Use prescribed topical medications as directed by your doctor",
    bullous_rec_4: "Avoid activities that may cause friction or trauma to the blistered areas",
    bullous_rec_5: "Seek medical attention promptly, as this condition often requires prescription treatment",
    drugeruption_rec_1: "Make a list of all medications and supplements you are currently taking",
    drugeruption_rec_2: "Do not stop any prescribed medication without consulting your doctor first",
    drugeruption_rec_3: "Contact your healthcare provider immediately to identify and review the suspected medication",
    drugeruption_rec_4: "Apply cool compresses or calamine lotion to soothe itchy or irritated skin",
    drugeruption_rec_5: "Seek emergency care if you experience difficulty breathing, swelling of the face or throat, or widespread blistering",
    eczema_rec_1: "Keep the skin well moisturized with fragrance-free emollients, especially after bathing",
    eczema_rec_2: "Avoid known triggers such as harsh soaps, detergents, extreme temperatures, and stress",
    eczema_rec_3: "Take lukewarm (not hot) showers and baths, and keep them short",
    eczema_rec_4: "Consider over-the-counter hydrocortisone cream for mild itching and inflammation",
    eczema_rec_5: "Consult a dermatologist if symptoms persist, worsen, or interfere with your daily life",
    lichen_rec_1: "Avoid scratching the affected areas to prevent further irritation and scarring",
    lichen_rec_2: "Use mild, fragrance-free skin care products and avoid harsh chemicals",
    lichen_rec_3: "Apply prescribed topical corticosteroids to reduce inflammation and itching",
    lichen_rec_4: "If mouth sores are present, avoid spicy and acidic foods that may worsen pain",
    lichen_rec_5: "Schedule a follow-up with a dermatologist for proper management and monitoring",
    lupus_rec_1: "Protect your skin strictly from the sun — use SPF 50+ sunscreen and reapply every 2 hours",
    lupus_rec_2: "Wear protective clothing, wide-brimmed hats, and UV-blocking sunglasses",
    lupus_rec_3: "Consult a rheumatologist or dermatologist for a comprehensive evaluation",
    lupus_rec_4: "Track your symptoms, flare-ups, and potential triggers in a daily journal",
    lupus_rec_5: "Follow up regularly with your healthcare team, as lupus may affect other organs beyond the skin",
    rosacea_rec_1: "Identify and avoid personal triggers such as hot drinks, spicy food, alcohol, and extreme temperatures",
    rosacea_rec_2: "Use gentle, fragrance-free skincare products designed for sensitive skin",
    rosacea_rec_3: "Apply a broad-spectrum sunscreen (SPF 30+) daily, as sun exposure is a major trigger",
    rosacea_rec_4: "Avoid rubbing or scrubbing the face — pat dry gently after washing",
    rosacea_rec_5: "See a dermatologist for prescription treatments that can effectively control symptoms",
    seborrh_keratoses_rec_1: "No treatment is usually necessary since seborrheic keratoses are benign",
    seborrh_keratoses_rec_2: "Do not scratch or pick at the growths, as this may cause irritation or infection",
    seborrh_keratoses_rec_3: "Monitor any growth for sudden changes in size, color, shape, or bleeding",
    seborrh_keratoses_rec_4: "See a dermatologist if the growth becomes irritated, bleeds, or you are uncertain about its nature",
    seborrh_keratoses_rec_5: "If cosmetically bothersome, ask your doctor about safe removal options such as cryotherapy",
    skincancer_rec_1: "Schedule an urgent appointment with a dermatologist or oncologist as soon as possible",
    skincancer_rec_2: "Do not attempt to treat, remove, or biopsy the lesion yourself",
    skincancer_rec_3: "Protect the area from further sun exposure while awaiting your appointment",
    skincancer_rec_4: "Take clear photos of the lesion to document any changes over the coming days",
    skincancer_rec_5: "Stay calm — many skin cancers are highly treatable when caught early with professional care",
    tinea_rec_1: "Apply over-the-counter antifungal cream, lotion, or spray as directed on the packaging",
    tinea_rec_2: "Keep the affected area clean and dry — fungi thrive in warm, moist environments",
    tinea_rec_3: "Avoid sharing towels, clothing, or personal items to prevent spreading the infection",
    tinea_rec_4: "Wash your hands thoroughly after touching the affected area",
    tinea_rec_5: "See a doctor if the infection does not improve within 2 weeks or spreads to larger areas",
    unknown_normal_rec_1: "If you have any symptoms or concerns, consult a dermatologist for a thorough examination",
    unknown_normal_rec_2: "Continue regular skincare routines and sun protection habits",
    unknown_normal_rec_3: "Monitor your skin for any new or changing spots, moles, or rashes",
    unknown_normal_rec_4: "Consider re-scanning if the image quality was poor, blurry, or taken in bad lighting",
    unknown_normal_rec_5: "Remember, the AI covers 15 specific conditions — other skin issues may still be present",
    vasculitis_rec_1: "Seek medical attention promptly, as vasculitis may require blood tests and further evaluation",
    vasculitis_rec_2: "Avoid activities that worsen swelling — elevate affected limbs when resting",
    vasculitis_rec_3: "Do not ignore symptoms like fever, fatigue, joint pain, or numbness alongside skin changes",
    vasculitis_rec_4: "Follow your doctor's prescribed treatment plan, which may include anti-inflammatory medications",
    vasculitis_rec_5: "Keep regular follow-up appointments to monitor the condition and adjust treatment as needed",
    vitiligo_rec_1: "Apply sunscreen (SPF 30+) to depigmented areas, as they burn easily without melanin protection",
    vitiligo_rec_2: "Consult a dermatologist to discuss treatment options such as topical corticosteroids or phototherapy",
    vitiligo_rec_3: "Use cosmetic camouflage products if the patches cause cosmetic concern",
    vitiligo_rec_4: "Protect your skin from cuts and sunburns, which may trigger new patches (Koebner phenomenon)",
    vitiligo_rec_5: "Consider emotional or psychological support if vitiligo is affecting your self-esteem or well-being",
    warts_rec_1: "Avoid picking, scratching, or biting warts to prevent spreading to other areas",
    warts_rec_2: "Try over-the-counter treatments containing salicylic acid as a first step",
    warts_rec_3: "Keep the area clean and covered with a bandage to reduce the risk of spreading",
    warts_rec_4: "Do not share personal items like towels, razors, or nail clippers",
    warts_rec_5: "See a dermatologist if warts are painful, spreading rapidly, or located on the face or genitals",

    // ─── Disease library card keys (short descriptions for library cards) ───
    eczema_desc: "A chronic inflammatory skin condition characterized by dry, itchy, and inflamed skin. Often associated with a personal or family history of atopy.",
    eczema_common: "Children, people with atopic history",
    eczema_symptoms: "Dryness, intense itching, red patches, scaling",
    acne_desc: "An inflammatory condition of the pilosebaceous unit, presenting with comedones, papules, pustules and sometimes nodules or cysts.",
    acne_common: "Adolescents and young adults",
    acne_symptoms: "Pimples, blackheads, whiteheads, possible scarring",
    psoriasis_desc: "A chronic immune-mediated skin disease marked by sharply demarcated scaly plaques, frequently on extensor surfaces and the scalp.",
    psoriasis_common: "Adults, variable onset",
    psoriasis_symptoms: "Well-defined red plaques with silvery scale, itching sometimes",

    // Month and weekday names
    month_0: "January",
    month_1: "February",
    month_2: "March",
    month_3: "April",
    month_4: "May",
    month_5: "June",
    month_6: "July",
    month_7: "August",
    month_8: "September",
    month_9: "October",
    month_10: "November",
    month_11: "December",

    day_0: "Sun",
    day_1: "Mon",
    day_2: "Tue",
    day_3: "Wed",
    day_4: "Thu",
    day_5: "Fri",
    day_6: "Sat",

    full_day_0: "Sunday",
    full_day_1: "Monday",
    full_day_2: "Tuesday",
    full_day_3: "Wednesday",
    full_day_4: "Thursday",
    full_day_5: "Friday",
    full_day_6: "Saturday",
    follow_up_expired: "Follow-up Expired",
    follow_up_active: "Follow-up Active",
    days_short: "d",
    hours_short: "h",
    minutes_short: "m",
    remaining: "remaining",
    report_required: "Report Required",
    doctors_report_click: "Doctor's Report — click to view",
    no_reviewed_cases: "No Reviewed Cases",
    no_reviewed_cases_desc: "There are no reviewed cases to display right now.",
    medical_report: "Medical Report",
    report_readonly_expired: "This report is read-only because the follow-up period has expired.",
    write_report_placeholder: "Write your medical report here...",
    submit_to_patient: "Submit to Patient",
    system_generated_ai: "System-generated AI Analysis",
    chat_secure_notice: "End-to-end encrypted conversation. Your privacy is protected.",
    no_messages_yet_dr: "No messages yet. Start the conversation with your patient.",
    messages_monitored_disclaimer: "Messages are monitored for quality assurance and training purposes",
    no_pending_cases: "No Pending Cases",
    no_pending_cases_desc: "There are no pending cases assigned to you at the moment.",
    submitting_report_dots: "Submitting report...",
    availability_saved: "Availability saved!",
    availability_save_error: "Could not save availability.",
    day_removed: "Day removed.",
    availability_remove_error: "Could not remove availability.",
    add_one_slot_error: "Add at least one time slot.",
    loading_dots: "Loading…",
  },
  ar: {
    // Navbar
    home: "الرئيسية",
    features: "المميزات",
    contact_us: "اتصل بنا",
    sign_in: "تسجيل الدخول",
    register: "إنشاء حساب",
    logout: "تسجيل الخروج",
    language: "اللغة",
    english: "English",
    arabic: "العربية",
    
    // Footer
    medical_disclaimer_title: "إخلاء مسؤولية طبي:",
    medical_disclaimer_desc: "تم تصميم نظام كشف الأمراض الجلدية للمساعدة في تحديد الحالة الجلدية ولكن لا ينبغي أن يحل محل الاستشارة الطبية المهنية أو التشخيص أو العلاج.",
    medical_disclaimer_advice: "اطلب دائماً مشورة طبيبك أو أي مقدم رعاية صحية مؤهل آخر لأي أسئلة تتعلق بحالة طبية.",
    footer_copyright: "© 2024 نظام كشف الأمراض الجلدية. منصة رعاية صحية متوافقة مع HIPAA.",
    
    // Auth & Forms
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    forgot_password: "نسيت كلمة المرور؟",
    sign_in_btn: "تسجيل الدخول",
    register_btn: "إنشاء حساب",
    full_name: "الاسم الكامل",
    phone: "رقم الهاتف",
    gender: "الجنس",
    male: "ذكر",
    female: "أنثى",
    age: "العمر",
    address: "العنوان",
    national_id: "الرقم القومي",
    specialization: "التخصص",
    experience: "سنوات الخبرة",
    clinic_address: "عنوان العيادة",
    consultation_fee: "قيمة الكشف",
    syndicate_card: "صورة بطاقة النقابة",
    patient: "مريض",
    doctor: "طبيب",
    register_as_patient: "التسجيل كمريض",
    register_as_doctor: "التسجيل كطبيب",
    sign_in_card_title: "تسجيل الدخول",
    sign_in_card_desc: "أدخل بيانات الاعتماد الخاصة بك للوصول إلى حسابك",
    i_am_a: "أنا",
    select_role: "اختر الدور",
    remember_me: "تذكرني",
    signing_in: "جاري تسجيل الدخول...",
    dont_have_account: "ليس لديك حساب؟",
    register_here: "سجل هنا",
    forgot_password_title: "نسيت كلمة المرور",
    forgot_password_desc: "أدخل بريدك الإلكتروني لتلقي رمز التحقق من إعادة تعيين كلمة المرور",
    forgot_password_desc_ext: "أدخل عنوان بريدك الإلكتروني وسنرسل لك رمز تحقق لإعادة تعيين كلمة المرور الخاصة بك",
    verify_otp_info: "سيتم إرسال رمز تحقق مكون من 6 أرقام إلى عنوان بريدك الإلكتروني المسجل.",
    send_verification_code: "إرسال رمز التحقق",
    remember_password: "هل تتذكر كلمة المرور الخاصة بك؟",
    send_code: "إرسال الرمز",
    sending: "جاري الإرسال...",
    back_to_sign_in: "العودة لتسجيل الدخول",
    verify_otp_title: "التحقق من الرمز",
    verify_otp_desc: "لقد أرسلنا رمزاً مكوناً من 6 أرقام إلى بريدك الإلكتروني",
    verify_otp_desc_sent: "أدخل رمز التحقق المكون من 6 أرقام المرسل إلى",
    verify_btn: "التحقق من الرمز",
    verifying: "جاري التحقق...",
    resend_code: "إعادة إرسال الرمز",
    resend_in: "إعادة الإرسال خلال",
    reset_password_title: "إعادة تعيين كلمة المرور",
    reset_password_desc: "أنشئ كلمة مرور جديدة وقوية لحسابك",
    reset_password_desc_for: "أنشئ كلمة مرور جديدة وقوية لـ",
    new_password: "كلمة المرور الجديدة",
    confirm_password: "تأكيد كلمة المرور الجديدة",
    reset_btn: "إعادة تعيين كلمة المرور",
    resetting: "جاري إعادة التعيين...",
    code_expires_in: "ينتهي صلاحية الرمز خلال:",
    code_expired: "انتهت صلاحية الرمز.",
    code_expired_desc: "يرجى إعادة الإرسال للحصول على رمز جديد.",
    identity_verified: "تم التحقق من هويتك. يرجى إنشاء كلمة مرور جديدة.",
    password_requirements: "متطلبات كلمة المرور:",
    pwd_req_1: "6 أحرف على الأقل",
    pwd_req_2: "استخدم مزيجاً من الحروف والأرقام والرموز",
    return_to_login: "العودة إلى صفحة تسجيل الدخول",
    verify_code_desc: "سيتم إرسال رمز تحقق مكون من 6 أرقام إلى عنوان بريدك الإلكتروني المسجل.",
    didnt_receive_code: "لم تستلم الرمز؟",

    // Features Section & CTA Section
    why_choose_system: "لماذا تختار نظام كشف الأمراض الجلدية؟",
    feature_ai_title: "تحليل مدعوم بالذكاء الاصطناعي",
    feature_ai_desc: "توفر خوارزميات التعلم الآلي المتقدمة تحديداً فورياً للحالة الجلدية الأولية",
    feature_expert_title: "تحقق الخبراء",
    feature_expert_desc: "تتم مراجعة جميع نتائج الذكاء الاصطناعي من قبل أخصائيين معتمدين في طب الأمراض الجلدية",
    feature_secure_title: "آمن وخاص",
    feature_secure_desc: "منصة متوافقة مع معايير HIPAA تضمن سرية بياناتك الصحية",
    feature_matching_title: "مطابقة الأطباء",
    feature_matching_desc: "تواصل مع المتخصصين المناسبين بناءً على حالتك",
    for_professionals: "لمتخصصي الرعاية الصحية",
    professionals_desc: "انضم إلى شبكتنا من الأطباء المعتمدين ومساعدة المرضى في الحصول على الرعاية التي يحتاجونها",
    benefit_1: "الوصول إلى حالات المرضى التي تم تحليلها بالذكاء الاصطناعي",
    benefit_2: "إدارة مبسطة للمرضى",
    benefit_3: "توسيع نطاق ممارستك",
    start_now: "ابدأ الآن",

    // Features Page
    platform_features: "مميزات المنصة",
    everything_needed_title: "كل ما تحتاجه من أجل",
    skin_health: " صحة الجلد",
    platform_desc: "من التشخيص المدعوم بالذكاء الاصطناعي إلى استشارات الأطباء المعتمدين، يجمع سكينر بين التكنولوجيا المتطورة والخبرة الطبية في منصة واحدة سلسة.",
    stat_ai: "مدعوم بالذكاء الاصطناعي",
    stat_ai_label: "تحليل الجلد",
    stat_verified: "معتمدون",
    stat_verified_label: "أطباء جلدية",
    stat_enc: "مشفرة بالكامل",
    stat_enc_label: "التسفير",
    stat_247: "24/7",
    stat_247_label: "مساعد الذكاء الاصطناعي",
    feat_ai_title: "تحليل الجلد بالذكاء الاصطناعي",
    feat_ai_desc: "حمّل صورة لحالتك الجلدية واحصل على تشخيص أولي فوري مدعوم بالذكاء الاصطناعي مع نسبة الثقة - كل ذلك في ثوانٍ.",
    feat_dr_title: "أطباء جلدية معتمدون",
    feat_dr_desc: "تصفح شبكة من أطباء الجلد المعتمدين. اعرض تخصصاتهم وخبراتهم وتقييماتهم ومواقع عياداتهم قبل الحجز.",
    feat_chat_title: "محادثة آمنة بين الطبيب والمريض",
    feat_chat_desc: "تواصل مع طبيب الجلدية الخاص بك من خلال رسائل مشفرة بالكامل. شارك الصور والملفات والمستندات مباشرة داخل المحادثة.",
    feat_booking_title: "حجز ذكي للمواعيد",
    feat_booking_desc: "احجز المواعيد مع توفرها في الوقت الفعلي. حدد التاريخ والوقت المفضلين لديك، واعرض جدول الطبيب، وأكد فوراً.",
    feat_payment_title: "مدفوعات آمنة باستخدام رمز الأمان",
    feat_payment_desc: "ادفع ثمن الاستشارات بشكل آمن من خلال معالجة متوافقة مع معايير PCI-DSS. يتم التحقق من كل عملية برمز أمان لمرة واحدة (OTP) لأقصى درجات الأمان.",
    feat_bot_title: "مساعد صحي بالذكاء الاصطناعي",
    feat_bot_desc: "احصل على إجابات فورية حول الحالات الجلدية، وخيارات العلاج، وإرشادات المنصة من روبوت الدردشة بالذكاء الاصطناعي المتوافق مع HIPAA - متوفر على مدار الساعة طوال الأسبوع.",
    feat_report_title: "التقارير الطبية والتنزيلات",
    feat_report_desc: "يمكن للأطباء كتابة تقارير طبية مفصلة مباشرة داخل المنصة. يتلقى المرضى تقارير قابلة للتنزيل ويمكنهم مراجعة سجل تشخيصهم.",
    feat_upload_title: "تحميل الصور ومراجعة الحالة",
    feat_upload_desc: "يقوم المرضى بتحميل صور الجلد لتحليلها. يراجع الأطباء الحالات بمعلومات كاملة عن المريض وتوقعات الذكاء الاصطناعي قبل الاستشارة.",
    feat_map_title: "خرائط مواقع العيادات",
    feat_map_desc: "عرض عيادة طبيبك على خريطة جوجل التفاعلية المدمجة. احصل على الاتجاهات للعنوان الدقيق لموعدك الشخصي.",
    feat_dash_title: "لوحة تحكم الطبيب والتحليلات",
    feat_dash_desc: "يدير الأطباء الحالات المعلقة والمراجعة، ويحددون جداول توفرهم، ويتتبعون تحليلات المرضى - كل ذلك من لوحة تحكم موحدة.",
    feat_privacy_title: "الخصوصية وحماية البيانات",
    feat_privacy_desc: "جميع المحادثات مشفرة بين الطرفين. يتم التعامل مع البيانات الطبية وفقاً لمعايير متوافقة مع HIPAA. تظل معلوماتك الصحية خاصة.",
    feat_library_title: "مكتبة التحليلات",
    feat_library_desc: "الوصول إلى مكتبة شاملة للتحليلات السابقة ومعلومات الحالة الجلدية. تتبع رحلة صحة بشرتك مع سجل كامل للنتائج.",
    ready_control: "هل أنت مستعد للسيطرة على صحة بشرتك؟",
    join_skinner_desc: "انضم إلى سكينر اليوم واحصل على تحليل للجلد مدعوم بالذكاء الاصطناعي، وأطباء جلدية معتمدين، واستشارات طبية آمنة - كل ذلك في منصة واحدة.",
    get_started_free: "ابدأ مجاناً",

    // Contact Us Page
    contact_desc: "لديك أسئلة حول سكينر؟ تواصل مع فريقنا - نحن هنا لمساعدتك في أي شيء يتعلق بصحة الجلد ومنصتنا.",
    phone_numbers: "أرقام الهواتف",
    email_addresses: "عناوين البريد الإلكتروني",
    our_location: "موقعنا",
    egypt_cairo_alex: "مصر — القاهرة والإسكندرية",
    serving_patients_region: "خدمة المرضى في جميع أنحاء المنطقة باستخدام طب الجلدية المدعوم بالذكاء الاصطناعي.",
    working_hours: "ساعات العمل",
    sunday_thursday: "الأحد – الخميس",
    friday_saturday: "الجمعة – السبت",
    nine_to_six: "9:00 ص – 6:00 م",
    closed: "مغلق",
    need_immediate_assistance: "هل تحتاج إلى مساعدة فورية؟",
    immediate_assistance_desc: "بالنسبة للمخاوف الطبية العاجلة، يرجى الاتصال بأقرب مقدم رعاية صحية أو الاتصال بخدمات الطوارئ.",
    call_us_now: "اتصل بنا الآن",
    
    // Portal General
    patient_portal: "بوابة المريض",
    doctor_portal: "بوابة الطبيب",
    admin_portal: "لوحة التحكم للمسؤول",
    
    // Stats & Tabs
    pending_reviews: "مراجعات معلقة",
    finished_cases: "الحالات المكتملة",
    total_patients: "إجمالي المرضى",
    cases_awaiting_review: "حالات بانتظار المراجعة",
    cases_completed: "حالات مكتملة",
    total_patients_served: "إجمالي المرضى المستفيدين",
    no_patients_yet: "لا يوجد مرضى بعد",
    
    pending_cases_tab: "الحالات المعلقة",
    finished_cases_tab: "الحالات المكتملة",
    schedule_tab: "الجدول الزمني",
    
    // Case details & Card
    case_review_title: "مراجعة الحالة",
    submitted_on: "تم الإرسال في",
    back_to_list: "العودة للقائمة",
    patient_info: "معلومات المريض",
    ai_analysis: "تحليل الذكاء الاصطناعي",
    confidence_level: "مستوى الثقة",
    write_report: "كتابة تقرير",
    view_report: "عرض التقرير",
    edit_report: "تعديل التقرير",
    start_chat: "بدء محادثة مع المريض",
    continue_chat: "متابعة المحادثة",
    read_chat: "قراءة المحادثة",
    follow_up_chat: "متابعة المحادثة",
    ai_diagnosis: "تشخيص الذكاء الاصطناعي",
    confidence: "مستوى الثقة",
    yrs: "سنة",
    review_case: "مراجعة الحالة",
    chat_with_patient: "محادثة المريض",
    
    // Chat & Summary Card
    clinical_summary: "الملخص السريري",
    ai_prediction: "توقع الذكاء الاصطناعي",
    analysis_date: "تاريخ التحليل",
    view_skin_scan: "عرض فحص الجلد",
    secure: "آمن",
    chat_locked: "تم قفل المحادثة لانتهاء فترة المتابعة.",
    type_message: "اكتب رسالة...",
    send: "إرسال",
    
    // Home Page
    hero_title: "ثورة في تشخيص أمراض الجلدية",
    hero_subtitle: "احصل على تصنيفات متطورة لأمراض الجلد بالذكاء الاصطناعي واستشر كبار الأطباء على الفور من منزلك.",
    get_started: "ابدأ الآن",
    learn_more: "تعرف على المزيد",
    features_title: "لماذا تختار سكينر؟",
    features_desc: "نحن نجمع بين الذكاء الاصطناعي المتطور والمتخصصين الطبيين المعتمدين لتقديم رعاية صحية فورية وموثوقة للجلد.",
    
    // Patient Portal Tabs & Elements
    upload_tab: "تحميل الصورة",
    analysis_tab: "التحليل",
    doctors_tab: "الأطباء",
    chat_tab: "المحادثة",
    patient_tab: "المريض",
    library_tab: "المكتبة الطبية",
    previous: "السابق",
    next: "التالي",
    scan_history: "سجل فحوصات الجلد",
    no_analyses_yet: "لم تقم بفحص أي حالات جلدية بعد.",
    view_details: "عرض التفاصيل",
    confidence_score: "درجة الثقة",
    find_doctors: "البحث عن أطباء",
    start_new_analysis: "بدء تحليل جديد",
    ai_health_assistant: "المساعد الصحي الذكي",
    ai_assistant_desc: "اطرح أي أسئلة حول الحالات الجلدية، أو الأعراض العامة، أو طريقة استخدام المنصة.",
    type_ai_question: "اسأل المساعد الصحي بالذكاء الاصطناعي...",
    
    // Upload Skin Image Card
    tip_1: "تأكد من وجود إضاءة جيدة بدون ظلال",
    tip_2: "التقط الصورة عمودية على سطح الجلد",
    tip_3: "قم بتضمين كائن مرجعي للمقياس إن أمكن",
    tip_4: "تجنب استخدام الفلاش قدر الإمكان",
    tip_5: "التقط المنطقة المصابة بالكامل",
    upload_skin_image: "تحميل صورة الجلد",
    upload_skin_desc: "التقط صورة واضحة أو حمّل صورة للمنطقة المصابة لتحليلها بالذكاء الاصطناعي",
    best_results: "للحصول على أفضل النتائج:",
    upload_from_device: "تحميل من الجهاز",
    browse_files: "انقر لتصفح الملفات",
    take_photo: "التقط صورة",
    use_camera: "استخدم الكاميرا الخاصة بك",
    supported_formats: "الصيغ المدعومة: JPG, PNG, HEIC - الحد الأقصى لحجم الملف:",
    saved_image_title: "الصورة المحفوظة - جاهزة للتحليل",
    saved_image_desc: "تم حفظ صورتك بشكل آمن وهي جاهزة للتحليل بالذكاء الاصطناعي",
    ai_progress_title: "تحليل الذكاء الاصطناعي قيد التنفيذ",
    ai_progress_desc: "جاري تحليل صورة بشرتك",
    analyzing: "جاري التحليل...",
    analyze_with_ai: "تحليل الصورة بالذكاء الاصطناعي",
    upload_new_image: "تحميل صورة جديدة",
    retake_photo: "إعادة التقاط الصورة",
    close: "إغلاق",
    
    // Register Extra
    register_desc: "التسجيل كمريض، أو مقدم رعاية صحية، أو مسؤول",
    already_have_account: "لديك حساب بالفعل؟",
    sign_in_here: "سجل الدخول هنا",
    upload_id: "تحميل بطاقة الهوية الخاصة بك",
    invite_code: "رمز الدعوة",
    register_as_admin: "التسجيل كمسؤول",
    terms_policy_agreement: "بالتسجيل، فإنك توافق على شروط الخدمة وسياسة الخصوصية الخاصة بنا.",
    doctor_review_agreement: "ستتم مراجعة تسجيلك من قبل فريق الإدارة لدينا.",
    admin_invite_warning: "تسجيل المسؤول: تتطلب حسابات المسؤول ترخيصاً ورمز دعوة.",

    report_submitted: "تم إرسال التقرير",
    all_reports: "جميع التقارير",
    report_doctor: "تقرير {name}",
    select_date_time_error: "يرجى تحديد تاريخ ووقت صالحين قبل المتابعة.",
    availability_load_error: "تعذر تحميل المواعيد المتاحة للطبيب من الخادم. يرجى المحاولة لاحقاً.",
    upload_analysis_required: "يرجى تحميل صورة الجلد وتحليلها قبل حجز موعد.",
    booking_failed: "تعذر حجز الموعد.",
    doctors_load_error: "تعذر تحميل قائمة الأطباء من الخادم. يرجى المحاولة لاحقاً.",
    missing_appointment_id: "رقم الموعد مفقود. يرجى حجز الموعد مرة أخرى.",
    payment_failed: "فشلت عملية الدفع. يرجى المحاولة مرة أخرى.",
    message_send_failed: "تعذر إرسال الرسالة إلى الخادم.",
    ai_welcome: "مرحباً {name}! أنا مساعدك الصحي بالذكاء الاصطناعي. يمكنني مساعدتك في الإجابة على الأسئلة المتعلقة بحالتك الجلدية، وتقديم معلومات صحية عامة، وإرشادك عبر المنصة. كيف يمكنني مساعدتك اليوم؟",
    no_conversations_yet: "لا توجد محادثات بعد",
    no_conversations_desc: "ستظهر محادثاتك مع الأطباء هنا بعد حجز موعد.",
    no_messages_yet: "لا توجد رسائل بعد. ألقِ التحية على طبيبك!",
    download_report: "تحميل التقرير",
    my_conversations: "محادثاتي",
    chat_securely_desc: "تحدث مع أطبائك بشكل آمن",
    high_confidence: "ثقة عالية",
    medium_confidence: "ثقة متوسطة",
    low_confidence: "ثقة منخفضة",
    file_size_error: "يجب أن يكون حجم الملف أقل من 10 ميجابايت.",

    // Added for Dashboards & Pages
    see_more: "عرض المزيد",
    all_analyses: "جميع التحليلات السابقة",
    no_image: "لا توجد صورة",
    no_analyses_desc: "لا يوجد لديك أي تحليلات محفوظة بعد. حمّل صورة لإنشاء تحليل للجلد.",
    refresh: "تحديث",
    previous_analyses: "التحليلات السابقة",
    no_previous_analyses: "لا توجد تحليلات سابقة",
    loaded_from_api: "تم التحميل من الواجهة البرمجية",
    no_analyses_found: "لم يتم العثور على تحليلات.",
    could_not_load_analyses: "تعذر تحميل التحليلات السابقة.",
    unknown_condition: "حالة غير معروفة",
    confidence_suffix: "درجة الثقة",
    high: "مرتفع",
    medium: "متوسط",
    low: "منخفض",
    more: "إضافية",
    loading_analysis: "جاري تحميل التحليل...",
    unable_to_load_analysis: "تعذر تحميل التحليل",
    retry: "إعادة المحاولة",
    no_analysis_available: "لا يوجد تحليل متاح",
    upload_to_receive_ai: "حمّل صورة للجلد لتلقي تحليل مدعوم بالذكاء الاصطناعي.",
    start_analysis: "بدء التحليل",
    ai_analysis_results: "نتائج تحليل الذكاء الاصطناعي",
    analysis_completed_on: "تم التحليل في",
    analysis_completed_unknown: "في تاريخ غير معروف",
    ai_powered: "مدعوم بالذكاء الاصطناعي",
    medical_disclaimer_capital: "إخلاء مسؤولية طبي:",
    medical_disclaimer_detailed: "تحليل الذكاء الاصطناعي هذا هو لأغراض معلوماتية فقط ولا ينبغي أن يحل محل الاستشارة الطبية المتخصصة. يرجى استشارة مقدم رعاية صحية مؤهل للحصول على التشخيص والعلاج المناسبين.",
    analyzed_image: "الصورة المحللة",
    no_image_available: "لا توجد صورة متاحة",
    primary_detection: "التشخيص الأساسي",
    condition_unavailable: "الحالة غير متوفرة",
    analysis_status: "حالة التحليل",
    analysis_complete: "اكتمل التحليل",
    description: "الوصف",
    no_description_available: "لا يوجد وصف متاح لهذا التحليل.",
    ai_recommendations: "توصيات الذكاء الاصطناعي",
    no_recommendations_available: "لا توجد توصيات محددة متاحة لهذا التحليل. يرجى استشارة طبيب جلدية للحصول على نصيحة مخصصة.",
    alternative_detections: "تشخيصات بديلة",
    no_alternative_detections: "لم يتم العثور على تشخيصات بديلة مهمة.",
    next_step_consult: "الخطوة التالية: استشر طبيباً متخصصاً",
    consult_recommendation: "بناءً على نتائج التحليل، نوصي باستشارة أخصائي أمراض جلدية لإجراء تقييم شامل وخطة علاج مخصصة.",
    find_recommended_doctors: "البحث عن أطباء موصى بهم",
    hipaa_compliant_encrypted: "متوافق مع HIPAA • مشفر",
    chatbot_warning: "يوفر برنامج الدردشة هذا معلومات عامة فقط وليس بديلاً عن الاستشارة الطبية المتخصصة.",
    powered_by_ai: "مدعوم بالذكاء الاصطناعي • مشفر من الطرفين",
    encrypted: "مشفر",
    ai_assistant_unavailable: "مساعد الذكاء الاصطناعي غير متاح حالياً. يرجى المحاولة مرة أخرى لاحقاً.",
    ai_no_answer: "تلقيت رسالتك، ولكن لم يتم إرجاع أي إجابة من خدمة المساعد الذكي.",
    no_library_content: "لا يوجد محتوى في المكتبة حالياً",
    no_library_content_desc: "مكتبة الأمراض الجلدية فارغة حالياً لعدم توفر بيانات من الخادم.",
    skin_disease_library: "مكتبة الأمراض الجلدية",
    definition: "التعريف",
    common_in: "شائع في",
    symptoms: "الأعراض",
    back_to_library: "العودة للمكتبة",
    definition_colon: "التعريف:",
    common_in_colon: "شائع في:",
    symptoms_colon: "الأعراض:",
    pending_payment: "في انتظار الدفع",
    confirmed: "مؤكد",
    cancelled: "ملغي",
    completed: "مكتمل",
    reviewed: "تمت مراجعته",
    appointment_schedule: "جدول المواعيد",
    appointment_day: "يوم الموعد",
    today: "اليوم",
    upcoming_appointments: "المواعيد القادمة",
    no_upcoming_appointments: "لا توجد مواعيد قادمة",
    pay_now: "ادفع الآن",
    patient_information: "معلومات المريض",
    edit: "تعديل",
    save_changes: "حفظ التغييرات",
    cancel: "إلغاء",
    profile_updated: "تم تحديث ملف المريض بنجاح.",
    profile_load_error: "تعذر تحميل بيانات المريض من الخادم. يرجى المحاولة لاحقاً.",
    profile_update_error: "تعذر تحديث الملف الشخصي على الخادم.",
    appointment_details: "تفاصيل الموعد",
    dermatologist: "طبيب جلدية",
    date: "التاريخ",
    time: "الوقت",
    open_in_google_maps: "الفتح في خرائط جوجل",
    related_scan_analysis: "تحليل الفحص ذو الصلة",
    ai_skin_classification: "تصنيف الجلد بالذكاء الاصطناعي",
    available_specialists: "الأخصائيون المتاحون",
    browse_verified_doctors: "تصفح الأطباء المعتمدين المسجلين في المنصة واحجز موعداً.",
    loading_doctors_api: "جاري تحميل الأطباء من الخادم...",
    no_specialists_available: "لا يوجد أخصائيون متاحون",
    no_specialists_desc: "لم نتمكن من العثور على أي أطباء لطلبك الآن. يرجى التحقق لاحقاً.",
    book_appointment: "حجز موعد",
    verified: "معتمد",
    no_address_available: "لا يوجد عنوان متاح",
    no_doctor_selected: "لم يتم تحديد طبيب",
    select_doctor_first: "حدد طبيباً من التوصيات قبل عرض الخريطة.",
    back_to_doctors: "العودة لقائمة الأطباء",
    recommended_specialists: "الأخصائيون الموصى بهم",
    back: "رجوع",
    clinic: "العيادة",
    contact: "اتصال",
    not_available: "غير متاح",
    hours_not_available: "الساعات غير متاحة",
    years_experience: "{n} سنوات خبرة",
    doctor: "الطبيب",
    specialty_dermatology: "الأمراض الجلدية",
    specialty_pediatric_dermatology: "أمراض جلدية للأطفال",
    specialty_cosmetic_surgery: "جراحة التجميل",
    address_cairo: "القاهرة",
    address_nile_st_cairo: "شارع النيل، القاهرة",
    currency_format: "{val} جنيه مصري",
    currency_unit: "جنيه مصري",
    amount_paid: "المبلغ المدفوع",
    select_date: "اختر التاريخ",
    choose_available_date: "اختر تاريخاً متاحاً لموعدك",
    loading_available_dates: "جاري تحميل التواريخ المتاحة...",
    no_available_dates: "لا توجد تواريخ متاحة لهذا الطبيب.",
    select_time_slot: "اختر الفترة الزمنية",
    available_slots_for: "الفترات الزمنية المتاحة ليوم",
    loading_available_slots: "جاري تحميل الفترات المتاحة...",
    no_available_slots: "لا توجد فترات زمنية متاحة لهذا التاريخ.",
    morning: "الصباح",
    afternoon: "المساء",
    selected: "محدد",
    available: "متاح",
    unavailable: "غير متاح",
    appointment_summary: "ملخص الموعد",
    in_person_at: "حضورياً في",
    booking_dots: "جاري الحجز...",
    proceed_to_payment: "المتابعة للدفع",
    redirect_payment_notice: "سيتم توجيهك إلى صفحة دفع آمنة لإكمال الحجز. لن يتم فرض أي رسوم حتى تؤكد الدفع.",
    prices_include_tax: "الأسعار تشمل ضريبة 20%",
    booking_fee: "رسوم الحجز",
    tax: "الضريبة",
    total: "الإجمالي",
    cancellation_policy: "سياسة الإلغاء:",
    cancellation_policy_desc: "إلغاء مجاني حتى 24 ساعة قبل الموعد. استرداد 50% للإلغاء خلال 24 ساعة.",
    card_number: "رقم البطاقة",
    cardholder_name: "اسم صاحب البطاقة",
    expiry_date: "تاريخ الانتهاء",
    cvv: "الرمز السري (CVV)",
    secure_payment: "دفع آمن",
    payment_encrypted_desc: "معلومات الدفع الخاصة بك مشفرة وآمنة",
    pci_dss_compliant: "متوافق مع معايير PCI DSS:",
    pci_dss_desc: "جميع المعاملات مشفرة باستخدام تشفير SSL القياسي بـ 256 بت. لا يتم حفظ تفاصيل بطاقتك على خوادمنا مطلقاً.",
    save_card_future: "حفظ هذه البطاقة بشكل آمن للمواعيد القادمة",
    otp_sent: "تم إرسال رمز التحقق!",
    otp_sent_desc: "تم إرسال رمز تحقق مكون من 6 أرقام إلى رقم الهاتف المرتبط ببطاقتك الائتمانية.",
    enter_otp: "أدخل رمز التحقق (OTP)",
    code_expires: "ينتهي صلاحية الرمز خلال",
    resend_otp: "إعادة إرسال الرمز",
    security_verification_title: "التحقق الأمني:",
    security_verification_desc: "بعد النقر فوق \"تأكيد الدفع\"، سيتم إرسال رمز أمان لمرة واحدة (OTP) إلى رقم الهاتف المرتبط ببطاقتك الائتمانية للتحقق الأمني.",
    confirm_payment: "تأكيد الدفع",
    processing: "جاري المعالجة...",
    final_payment_confirmation: "تأكيد الدفع النهائي",
    payment_agreement_desc: "بتأكيد هذا الدفع، فإنك توافق على شروط الخدمة وسياسة الخصوصية الخاصة بنا. مدفوعاتك محمية بتشفير SSL 256 بت والتحقق من رمز الأمان.",
    we_accept: "نحن نقبل:",
    back_appointment_selection: "العودة لاختيار الموعد",
    payment_successful: "تم الدفع بنجاح!",
    payment_success_desc: "تم تأكيد موعدك وإرسال بريد إلكتروني للتأكيد.",
    appointment_confirmation: "تأكيد الموعد",
    save_records_desc: "يرجى حفظ هذه المعلومات للرجوع إليها",
    confirmation_number: "رقم التأكيد:",
    download_receipt: "تحميل الإيصال",
    add_to_calendar: "إضافة إلى التقويم",
    whats_next: "ما هي الخطوات التالية؟",
    email_confirmation_title: "بريد تأكيد إلكتروني",
    email_confirmation_desc: "تم إرسال بريد إلكتروني مفصل للتأكيد مع إرشادات الموعد إلى بريدك الإلكتروني المسجل.",
    calendar_reminder_title: "تذكير التقويم",
    calendar_reminder_desc: "أضف هذا الموعد إلى تقويمك لتلقي تذكيرات قبل الموعد بـ 24 ساعة وساعة واحدة.",
    arrive_early_title: "الوصول مبكراً بـ 15 دقيقة",
    arrive_early_desc: "يرجى الوصول إلى العيادة قبل 15 دقيقة من موعدك المحدد لتسجيل الدخول.",
    prepare_info_title: "حضّر معلوماتك",
    prepare_info_desc: "أحضر أي سجلات طبية ذات صلة، نتائج الفحوصات السابقة، وقائمة بالأدوية الحالية إلى موعدك.",
    need_changes_title: "هل تحتاج إلى إجراء تغييرات؟",
    need_changes_desc: "إذا كنت بحاجة إلى إعادة تحديد موعدك أو إلغائه، يرجى الاتصال بنا قبل 24 ساعة على الأقل.",
    chat_with_this_doctor: "دردش مع هذا الطبيب",
    return_to_dashboard: "العودة للوحة التحكم",
    tap_to_open_conv: "انقر لفتح المحادثة",
    report_available: "التقرير متوفر",
    chat_closes_in: "فترة المتابعة نشطة. تُغلق المحادثة خلال",
    chat_locked_new_appt: "المحادثة مقفلة. احجز موعداً جديداً مع هذا الطبيب لإعادة فتحها.",
    empty_message: "(رسالة فارغة)",
    view_skin_scan: "عرض فحص الجلد",
    cases_unread: "حالة",
    pending_cases: "الحالات المعلقة",
    finished_cases: "الحالات المكتملة",
    schedule: "الجدول الزمني",
    case_review_colon: "مراجعة الحالة:",
    case_closed_expired: "تم إغلاق هذه الحالة. انتهت فترة المتابعة ولم يتم تقديم تقرير طبي.",
    report_required_passed: "التقرير مطلوب: لقد مر تاريخ الموعد. يرجى كتابة وتقديم التقرير الطبي قبل انتهاء فترة المتابعة.",
    patient_image: "صورة المريض",
    report_not_submitted: "لم يتم تقديم التقرير",
    view_edit_report: "عرض وتعديل التقرير",
    download_receipt_txt: "تحميل الإيصال",
    get_report: "الحصول على التقرير",
    write_report: "كتابة التقرير",
    enter_notes_comments: "أدخل ملاحظات التحقق والتعليقات...",
    back_to_chat: "العودة للدردشة",
    save: "حفظ",
    saving_dots: "جاري الحفظ...",
    remove_day: "إزالة اليوم",
    no_slots_set: "لم يتم تحديد فترات زمنية - أضف واحدة أدناه",
    time_slot_one: "فترة زمنية",
    time_slots_many: "فترات زمنية",
    add_slot: "إضافة فترة",
    select_date_calendar_desc: "حدد تاريخاً على التقويم لتعيين ساعات عملك",
    click_date_available: "انقر على تاريخ لتعيين ساعات عملك",
    has_availability: "متاح فيه مواعيد",
    start: "البداية",
    end: "النهاية",
    slot: "الفترة",
    remove_time_slot: "إزالة هذه الفترة الزمنية",
    doctor_information: "معلومات الطبيب",
    total_users: "إجمالي المستخدمين",
    no_users_yet: "لا يوجد مستخدمون بعد",
    registered_users: "مستخدمون مسجلون",
    active_doctors: "الأطباء النشطون",
    no_active_doctors: "لا يوجد أطباء نشطون بعد",
    verified_professionals: "متخصصون معتمدون",
    pending_approvals: "طلبات بانتظار الموافقة",
    none_pending: "لا توجد طلبات معلقة",
    require_verification: "تتطلب التحقق",
    ai_analyses: "تحليلات الذكاء الاصطناعي",
    total_analyses_performed: "إجمالي التحليلات التي تم إجراؤها",
    conditions_found: "الحالات المكتشفة",
    condition_breakdown: "توزيع الحالات المكتشفة",
    no_analysis_data: "لا تتوفر بيانات تحليل بعد.",
    recent_analyses: "التحليلات الأخيرة",
    no_analyses_recorded: "لم يتم تسجيل أي تحليلات بعد.",
    search_users_placeholder: "البحث بالاسم أو البريد أو الهاتف...",
    all_filter: "الكل",
    patients_filter: "المرضى",
    doctors_filter: "الأطباء",
    no_users_found: "لم يتم العثور على مستخدمين",
    no_users_match: "لا يوجد مستخدمون مسجلون يطابقون معايير البحث الخاصة بك.",
    registered_colon: "تاريخ التسجيل:",
    specialization_bold: "التخصص:",
    experience_bold: "الخبرة:",
    clinic_address_bold: "عنوان العيادة:",
    generate_admin_code: "إنشاء رمز دعوة للمسؤول",
    generate_admin_code_desc: "إنشاء رمز دعوة لمرة واحدة يمكن استخدامه لتسجيل حساب مسؤول جديد. يمكن استخدام كل رمز لمرة واحدة فقط.",
    generating_dots: "جاري الإنشاء...",
    generate_new_code: "إنشاء رمز جديد",
    admin_code_generated_success: "تم إنشاء رمز دعوة المسؤول بنجاح!",
    admin_code_generated_fail: "تم إنشاء الرمز ولكن تعذر قراءته من الاستجابة.",
    admin_code_generated_fail_err: "فشل إنشاء رمز دعوة المسؤول.",
    generated_invite_code: "رمز الدعوة المنشأ",
    copied_excl: "تم النسخ!",
    copy: "نسخ",
    share_code_desc: "شارك هذا الرمز مع المسؤول الجديد. يمكن استخدامه لمرة واحدة فقط لتسجيل حساب واحد.",
    no_active_invite_code: "لا يوجد رمز دعوة نشط حالياً",
    missing_syndicate_id: "رقم النقابة للطبيب مفقود.",
    admin_action_fail: "فشلت عملية المسؤول. يرجى المحاولة مرة أخرى.",
    doctor_approved_success: "تم قبول الطبيب بنجاح.",
    doctor_rejected_success: "تم رفض الطبيب بنجاح.",
    working_dots: "جاري العمل...",
    confirm_approval: "تأكيد القبول",
    confirm_rejection: "تأكيد الرفض",
    approve_confirm_question: "هل أنت متأكد أنك تريد قبول {name}؟ سيؤدي هذا إلى تفعيل حسابه.",
    reject_confirm_question: "هل أنت متأكد أنك تريد رفض {name}؟ سيتم تسجيل هذا الإجراء.",
    confirm_btn: "تأكيد",
    approve_activate_btn: "قبول وتفعيل الحساب",
    reject_application_btn: "رفض الطلب",
    verify_doctor_colon: "التحقق من الطبيب:",
    verify_alert_desc: "يرجى التحقق من المؤهلات الطبية قبل الموافقة على هذا الطلب. سيتم فحص جميع المعلومات مع قواعد بيانات الترخيص الطبي.",
    verification_notes: "ملاحظات التحقق",
    this_doctor: "هذا الطبيب",
    pending: "معلق",
    verify_info_id: "التحقق من وثيقة الهوية",
    doctor_id_title: "هوية الطبيب",
    id_doctor_placeholder: "هوية الطبيب",
    review_application_btn: "مراجعة الطلب",
    submission_date: "تاريخ التقديم",
    approved: "مقبول",
    rejected: "مرفوض",
    years: "سنوات",
    minute: "دقيقة",
    minutes: "دقائق",
    second: "ثانية",
    seconds: "ثوانٍ",
    doctor_verification: "التحقق من الأطباء",
    user_management: "إدارة المستخدمين",
    analytics: "التحليلات",
    invite_codes: "رموز الدعوة",
    could_not_load_analytics: "تعذر تحميل بيانات التحليلات. يرجى المحاولة مرة أخرى.",
    could_not_load_pending: "تعذر تحميل قائمة الأطباء المعلقين من الخادم.",
    could_not_load_users: "تعذر تحميل دليل المستخدمين من الخادم.",
    could_not_load_admin: "تعذر تحميل بيانات بوابة المسؤول. يرجى المحاولة مرة أخرى.",
    no_pending_doctors: "لا يوجد أطباء معلقون",
    no_pending_doctors_desc: "لا توجد طلبات تحقق لأطباء بانتظار المراجعة حالياً.",
    dermatology: "طب الأمراض الجلدية",
    invite_code_used_success: "تم استخدام رمز الدعوة {code} بنجاح بواسطة {email}!",
    new_admin: "مسؤول جديد",

    // ─── أسماء الأمراض (جميع 16 حالة في نموذج الذكاء الاصطناعي) ───
    moles_title: "الشامات (الوحمات الصباغية)",
    acne_title: "حب الشباب الشائع",
    actinic_keratosis_title: "التقران السفعي",
    bullous_title: "مرض الفقاع",
    drugeruption_title: "طفح دوائي",
    eczema_title: "الأكزيما (التهاب الجلد التأتبي)",
    lichen_title: "الحزاز المسطح",
    lupus_title: "الذئبة الجلدية",
    rosacea_title: "الوردية",
    seborrh_keratoses_title: "التقرن الدهني",
    skincancer_title: "سرطان الجلد",
    tinea_title: "التينيا (السعفة)",
    unknown_normal_title: "غير معروف / طبيعي",
    vasculitis_title: "التهاب الأوعية الدموية",
    vitiligo_title: "البهاق",
    warts_title: "الثآليل (فيروس الورم الحليمي)",

    // ─── وصف الأمراض (نص كامل للمريض) ───
    moles_description: "الشامات (الوحمات الصباغية) هي نموّات جلدية شائعة تظهر كبقع صغيرة بنية داكنة ناتجة عن تجمّعات من الخلايا المنتجة للصبغة. معظم الشامات غير ضارة ونادراً ما تتحول إلى سرطان. يمكن أن تظهر في أي مكان على الجسم ومعظمها يتطور قبل سن الأربعين. من المهم مراقبتها لأي تغييرات.",
    acne_description: "حب الشباب هو حالة جلدية شائعة تحدث عندما تنسد بصيلات الشعر بالزيت وخلايا الجلد الميتة. غالباً ما يسبب البثور والرؤوس السوداء أو البيضاء ويظهر عادة على الوجه والجبهة والصدر وأعلى الظهر والكتفين. حب الشباب أكثر شيوعاً بين المراهقين ولكنه يمكن أن يصيب الأشخاص في جميع الأعمار.",
    actinic_keratosis_description: "التقران السفعي هو بقعة خشنة ومتقشرة على الجلد ناتجة عن سنوات من التعرض لأشعة الشمس. عادة ما يظهر على المناطق المعرضة للشمس مثل الوجه والشفتين والأذنين والساعدين وفروة الرأس والرقبة. على الرغم من أنه ليس سرطاناً، إلا أنه يُعتبر حالة سابقة للتسرطن لأنه قد يتحول أحياناً إلى سرطان الخلايا الحرشفية إذا تُرك دون علاج.",
    bullous_description: "مرض الفقاع يشير إلى مجموعة من الحالات التي تسبب فقاعات كبيرة مملوءة بالسوائل على الجلد. يمكن أن تظهر هذه الفقاعات على مناطق الجلد التي تنثني مثل أسفل البطن وأعلى الفخذين أو الإبطين. الحالة يمكن أن تكون مؤلمة وقد تزيد من خطر التهابات الجلد إذا انفجرت الفقاعات.",
    drugeruption_description: "الطفح الدوائي هو رد فعل جلدي ناتج عن دواء تتناوله. يمكن أن يظهر على شكل طفح جلدي أحمر أو شرى أو فقاعات أو تهيج جلدي واسع الانتشار. قد يبدأ التفاعل خلال أيام من بدء دواء جديد أو حتى بعد تناول الدواء لفترة طويلة. غالباً ما تتحسن الأعراض بمجرد إيقاف الدواء المسبب.",
    eczema_description: "الأكزيما (التهاب الجلد التأتبي) هي حالة مزمنة تجعل الجلد أحمر ومثيراً للحكة وملتهباً. غالباً ما تظهر على شكل بقع على اليدين والقدمين والكاحلين والمعصمين والرقبة وأعلى الصدر والجفون وداخل ثنيات المرفقين والركبتين. لا يوجد علاج نهائي لها ولكن الإدارة السليمة يمكن أن تسيطر على النوبات.",
    lichen_description: "الحزاز المسطح هو حالة التهابية تصيب الجلد والشعر والأظافر والأغشية المخاطية. على الجلد يظهر عادة كنتوءات أرجوانية مسطحة القمة ومثيرة للحكة. يمكن أن يسبب أيضاً بقعاً بيضاء شبكية أو تقرحات مؤلمة في الفم. الحالة غير معدية ويُعتقد أنها مرتبطة بالجهاز المناعي.",
    lupus_description: "الذئبة الجلدية تسبب طفحاً جلدياً وتقرحات متنوعة على الجلد بما في ذلك الطفح المميز على شكل فراشة عبر الخدين والأنف. هي حالة مناعة ذاتية حيث يهاجم الجهاز المناعي الأنسجة السليمة. أعراض الجلد قد تكون أول علامة على الذئبة ويمكن أن تتفاقم بالتعرض للشمس.",
    rosacea_description: "الوردية هي حالة جلدية مزمنة تسبب احمراراً وأوعية دموية مرئية وأحياناً نتوءات صغيرة مملوءة بالقيح على الوجه. تصيب عادة الخدين والأنف والذقن والجبهة. قد تشتد الأعراض لأسابيع أو أشهر ثم تختفي لفترة. بدون علاج تميل الوردية إلى التفاقم مع مرور الوقت.",
    seborrh_keratoses_description: "التقرن الدهني هو نمو جلدي شائع وغير ضار (غير سرطاني) يظهر عادة كبقعة شمعية بنية أو سوداء أو بلون الجلد مرتفعة قليلاً. غالباً ما تبدو وكأنها ملتصقة بالجلد ويمكن أن تظهر على الوجه والصدر والكتفين أو الظهر. على الرغم من أنها غير خطيرة إلا أنها قد تُخلط أحياناً مع سرطان الجلد.",
    skincancer_description: "اكتشف التحليل ملامح متوافقة مع سرطان الجلد. سرطان الجلد هو نمو غير طبيعي لخلايا الجلد يتطور غالباً على الجلد المعرض للشمس. الكشف المبكر والعلاج ضروريان للحصول على أفضل النتائج. يرجى عدم التأخير — يُنصح بشدة بإجراء تقييم طبي متخصص.",
    tinea_description: "التينيا (السعفة) هي عدوى فطرية شائعة تصيب الجلد وليست ناتجة عن دودة رغم الاسم. تظهر عادة كبقعة دائرية حمراء ومتقشرة ومثيرة للحكة مع جلد أنظف في المركز مكونة شكل حلقة. يمكن أن تظهر على الجسم وفروة الرأس والقدمين أو منطقة الفخذ وهي معدية عن طريق ملامسة الجلد أو الأدوات المشتركة.",
    unknown_normal_description: "لم يكتشف تحليل الذكاء الاصطناعي أياً من الحالات الجلدية الـ 15 المحددة التي تم تدريبه على تحديدها. قد يعني هذا أن الجلد يبدو طبيعياً أو أن الحالة خارج نطاق ما يغطيه نموذج الذكاء الاصطناعي. هذه النتيجة لا تستبعد جميع الحالات الجلدية.",
    vasculitis_description: "التهاب الأوعية الدموية هو حالة تتضمن التهاب الأوعية الدموية. عندما يصيب الجلد يمكن أن يسبب بقعاً أو نتوءات حمراء أو أرجوانية. في بعض الحالات قد تشير التغيرات الجلدية إلى حالة أكثر انتشاراً تصيب أعضاء أخرى. تتفاوت الشدة بشكل كبير حسب نوع ومدى إصابة الأوعية الدموية.",
    vitiligo_description: "البهاق هو حالة تفقد فيها بقع من الجلد لونها (الصبغة) مما ينتج عنه مناطق بيضاء ناعمة. يحدث عندما يتم تدمير الخلايا المنتجة للميلانين (صبغة الجلد) بواسطة الجهاز المناعي. يمكن أن يصيب البهاق أي منطقة من الجسم وقد ينتشر مع مرور الوقت. وهو غير معدٍ وغير ضار جسدياً ولكن قد يكون له تأثير نفسي.",
    warts_description: "الثآليل هي نموّات جلدية صغيرة وخشنة تسببها فيروس الورم الحليمي البشري (HPV). تكون أكثر شيوعاً على الأصابع واليدين ولكن يمكن أن تظهر في أي مكان من الجسم. الثآليل معدية ويمكن أن تنتشر عن طريق ملامسة الجلد المباشرة أو الأسطح الملوثة. معظم الثآليل غير ضارة وقد تختفي من تلقاء نفسها مع الوقت.",

    // ─── توصيات الأمراض ───
    moles_rec_1: "راقب شاماتك بانتظام لأي تغييرات في الحجم أو الشكل أو اللون أو التماثل (استخدم قاعدة ABCDE)",
    moles_rec_2: "احمِ الشامات من التعرض للشمس بوضع واقي شمس (SPF 30+) وارتداء ملابس واقية",
    moles_rec_3: "لا تحاول إزالة أو خدش الشامات في المنزل — فقد يسبب ذلك عدوى أو تندباً",
    moles_rec_4: "راجع طبيب جلدية إذا تغير مظهر الشامة أو نزفت أو أصبحت مؤلمة أو مثيرة للحكة",
    moles_rec_5: "فكّر في إجراء فحوصات جلدية سنوية مع طبيب جلدية خاصة إذا كان لديك شامات كثيرة أو تاريخ عائلي لسرطان الجلد",
    acne_rec_1: "اغسل المنطقة المصابة برفق مرتين يومياً بغسول لطيف وخالٍ من العطور",
    acne_rec_2: "تجنب لمس البثور أو عصرها أو خدشها لمنع التندب والعدوى",
    acne_rec_3: "استخدم مرطبات وواقيات شمس لا تسد المسام (غير كوميدوغينية)",
    acne_rec_4: "فكّر في استخدام علاجات بدون وصفة طبية تحتوي على بنزويل بيروكسيد أو حمض الساليسيليك",
    acne_rec_5: "استشر طبيب جلدية إذا كان حب الشباب شديداً أو مؤلماً أو لا يتحسن بالعناية الأساسية",
    actinic_keratosis_rec_1: "ضع واقي شمس واسع الطيف (SPF 30+) يومياً حتى في الأيام الغائمة",
    actinic_keratosis_rec_2: "ارتدِ ملابس واقية وقبعات ونظارات شمسية عند الخروج",
    actinic_keratosis_rec_3: "حدد موعداً مع طبيب جلدية للتقييم المهني في أقرب وقت ممكن",
    actinic_keratosis_rec_4: "تجنب أسِرّة التسمير والتعرض المباشر المطول لأشعة الشمس",
    actinic_keratosis_rec_5: "راقب المنطقة المصابة لأي تغييرات في الحجم أو اللون أو الملمس وأبلغ طبيبك",
    bullous_rec_1: "لا تفقع أو تثقب الفقاعات — أبقِها سليمة لمنع العدوى",
    bullous_rec_2: "حافظ على نظافة المنطقة المصابة وقم بتغطيتها برفق بضمادات معقمة",
    bullous_rec_3: "استخدم الأدوية الموضعية الموصوفة وفقاً لتوجيهات طبيبك",
    bullous_rec_4: "تجنب الأنشطة التي قد تسبب احتكاكاً أو صدمة للمناطق المصابة بالفقاعات",
    bullous_rec_5: "اطلب الرعاية الطبية على الفور حيث تتطلب هذه الحالة غالباً علاجاً بوصفة طبية",
    drugeruption_rec_1: "أعدّ قائمة بجميع الأدوية والمكملات التي تتناولها حالياً",
    drugeruption_rec_2: "لا توقف أي دواء موصوف دون استشارة طبيبك أولاً",
    drugeruption_rec_3: "اتصل بمقدم الرعاية الصحية فوراً لتحديد ومراجعة الدواء المشتبه به",
    drugeruption_rec_4: "ضع كمادات باردة أو مستحضر كالامين لتهدئة الجلد المتهيج أو المثير للحكة",
    drugeruption_rec_5: "اطلب رعاية طبية طارئة إذا واجهت صعوبة في التنفس أو تورم الوجه أو الحلق أو تفقعات واسعة الانتشار",
    eczema_rec_1: "حافظ على ترطيب الجلد جيداً بمرطبات خالية من العطور خاصة بعد الاستحمام",
    eczema_rec_2: "تجنب المحفزات المعروفة مثل الصابون القاسي والمنظفات ودرجات الحرارة القصوى والإجهاد",
    eczema_rec_3: "خذ دُشاً فاتراً (وليس ساخناً) واجعله قصيراً",
    eczema_rec_4: "فكّر في استخدام كريم هيدروكورتيزون بدون وصفة طبية للحكة والالتهاب الخفيف",
    eczema_rec_5: "استشر طبيب جلدية إذا استمرت الأعراض أو ساءت أو أثرت على حياتك اليومية",
    lichen_rec_1: "تجنب خدش المناطق المصابة لمنع المزيد من التهيج والتندب",
    lichen_rec_2: "استخدم منتجات العناية بالبشرة اللطيفة والخالية من العطور وتجنب المواد الكيميائية القاسية",
    lichen_rec_3: "ضع الكورتيكوستيرويدات الموضعية الموصوفة لتقليل الالتهاب والحكة",
    lichen_rec_4: "إذا كانت هناك تقرحات في الفم تجنب الأطعمة الحارة والحمضية التي قد تزيد الألم",
    lichen_rec_5: "حدد موعد متابعة مع طبيب جلدية للإدارة والمراقبة المناسبة",
    lupus_rec_1: "احمِ بشرتك بشكل صارم من الشمس — استخدم واقي شمس SPF 50+ وأعد وضعه كل ساعتين",
    lupus_rec_2: "ارتدِ ملابس واقية وقبعات عريضة الحواف ونظارات حاجبة للأشعة فوق البنفسجية",
    lupus_rec_3: "استشر طبيب روماتيزم أو طبيب جلدية لإجراء تقييم شامل",
    lupus_rec_4: "تتبع أعراضك ونوبات التفاقم والمحفزات المحتملة في مذكرة يومية",
    lupus_rec_5: "تابع بانتظام مع فريق الرعاية الصحية حيث قد تؤثر الذئبة على أعضاء أخرى غير الجلد",
    rosacea_rec_1: "حدد وتجنب المحفزات الشخصية مثل المشروبات الساخنة والطعام الحار والكحول ودرجات الحرارة القصوى",
    rosacea_rec_2: "استخدم منتجات العناية بالبشرة اللطيفة الخالية من العطور والمصممة للبشرة الحساسة",
    rosacea_rec_3: "ضع واقي شمس واسع الطيف (SPF 30+) يومياً حيث أن التعرض للشمس محفز رئيسي",
    rosacea_rec_4: "تجنب فرك أو حك الوجه — جفف بلطف بالتربيت بعد الغسيل",
    rosacea_rec_5: "راجع طبيب جلدية للحصول على علاجات بوصفة طبية يمكنها السيطرة على الأعراض بفعالية",
    seborrh_keratoses_rec_1: "لا يحتاج عادة إلى علاج لأن التقرن الدهني حميد",
    seborrh_keratoses_rec_2: "لا تخدش أو تنزع النموات لأن ذلك قد يسبب تهيجاً أو عدوى",
    seborrh_keratoses_rec_3: "راقب أي نمو لتغييرات مفاجئة في الحجم أو اللون أو الشكل أو النزيف",
    seborrh_keratoses_rec_4: "راجع طبيب جلدية إذا أصبح النمو متهيجاً أو نزف أو كنت غير متأكد من طبيعته",
    seborrh_keratoses_rec_5: "إذا كان مزعجاً من الناحية التجميلية اسأل طبيبك عن خيارات الإزالة الآمنة مثل العلاج بالتبريد",
    skincancer_rec_1: "حدد موعداً عاجلاً مع طبيب جلدية أو أخصائي أورام في أقرب وقت ممكن",
    skincancer_rec_2: "لا تحاول علاج أو إزالة أو أخذ عينة من الآفة بنفسك",
    skincancer_rec_3: "احمِ المنطقة من مزيد من التعرض للشمس أثناء انتظار موعدك",
    skincancer_rec_4: "التقط صوراً واضحة للآفة لتوثيق أي تغييرات خلال الأيام القادمة",
    skincancer_rec_5: "ابقَ هادئاً — العديد من سرطانات الجلد قابلة للعلاج بشكل كبير عند اكتشافها مبكراً بالرعاية المتخصصة",
    tinea_rec_1: "ضع كريم أو لوشن أو بخاخ مضاد للفطريات بدون وصفة طبية وفقاً للتعليمات",
    tinea_rec_2: "حافظ على نظافة وجفاف المنطقة المصابة — تزدهر الفطريات في البيئات الدافئة والرطبة",
    tinea_rec_3: "تجنب مشاركة المناشف والملابس والأدوات الشخصية لمنع انتشار العدوى",
    tinea_rec_4: "اغسل يديك جيداً بعد لمس المنطقة المصابة",
    tinea_rec_5: "راجع طبيباً إذا لم تتحسن العدوى خلال أسبوعين أو انتشرت إلى مناطق أكبر",
    unknown_normal_rec_1: "إذا كان لديك أي أعراض أو مخاوف استشر طبيب جلدية لإجراء فحص شامل",
    unknown_normal_rec_2: "استمر في روتين العناية بالبشرة وعادات الحماية من الشمس",
    unknown_normal_rec_3: "راقب بشرتك لأي بقع أو شامات أو طفح جلدي جديد أو متغير",
    unknown_normal_rec_4: "فكّر في إعادة الفحص إذا كانت جودة الصورة ضعيفة أو ضبابية أو مأخوذة في إضاءة سيئة",
    unknown_normal_rec_5: "تذكر أن الذكاء الاصطناعي يغطي 15 حالة محددة — قد تكون مشاكل جلدية أخرى لا تزال موجودة",
    vasculitis_rec_1: "اطلب الرعاية الطبية على الفور حيث قد يتطلب التهاب الأوعية الدموية فحوصات دم وتقييماً إضافياً",
    vasculitis_rec_2: "تجنب الأنشطة التي تزيد التورم — ارفع الأطراف المصابة عند الراحة",
    vasculitis_rec_3: "لا تتجاهل أعراضاً مثل الحمى والإرهاق وآلام المفاصل أو الخدر المصاحب لتغيرات الجلد",
    vasculitis_rec_4: "اتبع خطة العلاج الموصوفة من طبيبك والتي قد تشمل أدوية مضادة للالتهاب",
    vasculitis_rec_5: "حافظ على مواعيد المتابعة المنتظمة لمراقبة الحالة وتعديل العلاج حسب الحاجة",
    vitiligo_rec_1: "ضع واقي شمس (SPF 30+) على المناطق فاقدة الصبغة لأنها تحترق بسهولة بدون حماية الميلانين",
    vitiligo_rec_2: "استشر طبيب جلدية لمناقشة خيارات العلاج مثل الكورتيكوستيرويدات الموضعية أو العلاج بالضوء",
    vitiligo_rec_3: "استخدم منتجات التمويه التجميلية إذا كانت البقع تسبب قلقاً تجميلياً",
    vitiligo_rec_4: "احمِ بشرتك من الجروح وحروق الشمس التي قد تحفز ظهور بقع جديدة (ظاهرة كوبنر)",
    vitiligo_rec_5: "فكّر في الحصول على دعم نفسي أو عاطفي إذا كان البهاق يؤثر على تقديرك لذاتك أو صحتك النفسية",
    warts_rec_1: "تجنب نقر أو خدش أو عض الثآليل لمنع انتشارها إلى مناطق أخرى",
    warts_rec_2: "جرب العلاجات بدون وصفة طبية التي تحتوي على حمض الساليسيليك كخطوة أولى",
    warts_rec_3: "حافظ على نظافة المنطقة وقم بتغطيتها بضمادة لتقليل خطر الانتشار",
    warts_rec_4: "لا تشارك الأدوات الشخصية مثل المناشف والشفرات وأدوات قص الأظافر",
    warts_rec_5: "راجع طبيب جلدية إذا كانت الثآليل مؤلمة أو تنتشر بسرعة أو موجودة على الوجه أو المنطقة التناسلية",

    // ─── مفاتيح بطاقات مكتبة الأمراض (أوصاف مختصرة لبطاقات المكتبة) ───
    eczema_desc: "حالة جلدية التهابية مزمنة تتميز بجفاف الجلد والحكة والالتهاب. غالباً ما ترتبط بتاريخ شخصي أو عائلي للتأتب.",
    eczema_common: "الأطفال، الأشخاص الذين لديهم تاريخ تأتبي",
    eczema_symptoms: "الجفاف، الحكة الشديدة، بقع حمراء، تقشر",
    acne_desc: "حالة التهابية تصيب الوحدة الشعرية الدهنية، تظهر على شكل رؤوس سوداء، بثور، وأحياناً عقد أو أكياس.",
    acne_common: "المراهقون والشباب",
    acne_symptoms: "بثور، رؤوس سوداء، رؤوس بيضاء، ندبات محتملة",
    psoriasis_desc: "مرض جلدي مزمن بوساطة مناعية يتميز بلويحات قشرية محددة بوضوح، تظهر بشكل متكرر على الأسطح الباسطة وفروة الرأس.",
    psoriasis_common: "البالغون، بداية متغيرة",
    psoriasis_symptoms: "لويحات حمراء محددة جيداً مع قشور فضية، حكة أحياناً",

    // Month and weekday names
    month_0: "يناير",
    month_1: "فبراير",
    month_2: "مارس",
    month_3: "أبريل",
    month_4: "مايو",
    month_5: "يونيو",
    month_6: "يوليو",
    month_7: "أغسطس",
    month_8: "سبتمبر",
    month_9: "أكتوبر",
    month_10: "نوفمبر",
    month_11: "ديسمبر",

    day_0: "الأحد",
    day_1: "الاثنين",
    day_2: "الثلاثاء",
    day_3: "الأربعاء",
    day_4: "الخميس",
    day_5: "الجمعة",
    day_6: "السبت",

    full_day_0: "الأحد",
    full_day_1: "الاثنين",
    full_day_2: "الثلاثاء",
    full_day_3: "الأربعاء",
    full_day_4: "الخميس",
    full_day_5: "الجمعة",
    full_day_6: "السبت",
    follow_up_expired: "انتهت فترة المتابعة",
    follow_up_active: "فترة المتابعة نشطة",
    days_short: "يوم",
    hours_short: "ساعة",
    minutes_short: "دقيقة",
    remaining: "متبقية",
    report_required: "التقرير مطلوب",
    doctors_report_click: "تقرير الطبيب - انقر للعرض",
    no_reviewed_cases: "لا توجد حالات مراجعة بعد",
    no_reviewed_cases_desc: "لا توجد أي حالات تمت مراجعتها لعرضها الآن.",
    medical_report: "التقرير الطبي",
    report_readonly_expired: "هذا التقرير للقراءة فقط لأن فترة المتابعة قد انتهت.",
    write_report_placeholder: "اكتب تقريرك الطبي هنا...",
    submit_to_patient: "إرسال إلى المريض",
    system_generated_ai: "تحليل الذكاء الاصطناعي من النظام",
    chat_secure_notice: "محادثة مشفرة بالكامل بين الطرفين. خصوصيتك محمية.",
    no_messages_yet_dr: "لا توجد رسائل بعد. ابدأ المحادثة مع المريض.",
    messages_monitored_disclaimer: "تتم مراقبة الرسائل لضمان الجودة وأغراض التدريب",
    no_pending_cases: "لا توجد حالات معلقة",
    no_pending_cases_desc: "لا توجد حالات معلقة معينة لك في الوقت الحالي.",
    submitting_report_dots: "جاري تقديم التقرير...",
    availability_saved: "تم حفظ المواعيد المتاحة!",
    availability_save_error: "فشل في حفظ المواعيد المتاحة.",
    day_removed: "تم إزالة اليوم.",
    availability_remove_error: "فشل في إزالة المواعيد المتاحة.",
    add_one_slot_error: "يرجى إضافة فترة زمنية واحدة على الأقل.",
    loading_dots: "جاري التحميل...",
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem("skinner_lang") || "en";
  });

  useEffect(() => {
    localStorage.setItem("skinner_lang", lang);
    // Automatically apply HTML dir and lang attributes for RTL/Arabic layout support
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  }, [lang]);

  const toggleLanguage = () => {
    setLang((prev) => (prev === "en" ? "ar" : "en"));
  };

  const t = (key) => {
    return dictionary[lang]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useTranslation must be used within a LanguageProvider");
  }
  return context;
}

export default LanguageContext;

